'use strict';
const crypto=require('crypto');
const {BlobServiceClient}=require('@azure/storage-blob');

const TEAM_CONTAINER=process.env.EXPORTHUB_STORAGE_CONTAINER||process.env.EXPORTHUB_CONTAINER||'exporthub-data';
const TEAM_BLOB=process.env.EXPORTHUB_STORAGE_BLOB||process.env.EXPORTHUB_STATE_BLOB||'team-state.json';
const AUTH_BLOB=process.env.EXPORTHUB_AUTH_BLOB||'auth-sessions.json';
const GRAPH_BASE='https://graph.microsoft.com/v1.0';
const REFERENCE_FOLDER=(process.env.EXPORTHUB_REFERENCE_FOLDER||'003 Export/ExportHub/Sendungen').replace(/^\/+|\/+$/g,'');
const DRIVE_USER=process.env.EXPORTHUB_REFERENCE_DRIVE_USER||process.env.EXPORTHUB_POD_DRIVE_USER||'tobiaslimberg@essentra.com';
const MAX_FILE_BYTES=35*1024*1024;
let graphTokenCache=null;

function text(v){return String(v==null?'':v).trim()}
function lower(v){return text(v).toLowerCase()}
function json(status,body,headers){return{status,headers:Object.assign({'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'},headers||{}),body:JSON.stringify(body)}}
function error(code,message,status){const e=new Error(message||code);e.code=code||'SERVER_ERROR';e.status=Number(status||500);return e}
function connectionString(){return process.env.EXPORTHUB_STORAGE_CONNECTION_STRING||process.env.AzureWebJobsStorage||''}
function safeEqualText(a,b){const aa=Buffer.from(String(a||''),'utf8'),bb=Buffer.from(String(b||''),'utf8');return aa.length===bb.length&&aa.length>0&&crypto.timingSafeEqual(aa,bb)}
function tokenHash(token){return crypto.createHash('sha256').update(String(token||'')).digest('hex')}
function usernameOf(user){return lower(user&&(user.user||user.login||user.username||user.name))}
function isActive(user){return Boolean(user&&user.active!==false&&user.disabled!==true&&lower(user.status)!=='deaktiviert')}
function signingSecret(){const configured=text(process.env.EXPORTHUB_AUTH_SIGNING_SECRET||process.env.EXPORTHUB_SESSION_SECRET),source=configured||connectionString();if(!source)throw error('AUTH_SIGNING_NOT_CONFIGURED','Die sichere Sitzungssignatur ist serverseitig nicht konfiguriert.',503);return crypto.createHash('sha256').update('ExportHUB/session/v1|'+source).digest()}
function verifySignedSessionToken(token){const parts=text(token).split('.');if(parts.length!==3||parts[0]!=='ehs1')return null;const expected=crypto.createHmac('sha256',signingSecret()).update(parts[1]).digest('base64url');if(!safeEqualText(expected,parts[2]))return null;let p;try{p=JSON.parse(Buffer.from(parts[1],'base64url').toString('utf8'))}catch(_){return null}if(!p||p.purpose!=='exporthub-session'||Number(p.v||0)!==1||!p.uid||!p.sid||Number(p.exp||0)<=Date.now())return null;return p}
function bearer(req){const h=req&&req.headers||{},dedicated=h['x-exporthub-token']||h['X-ExportHUB-Token']||h['x-exporthub-session']||h['X-ExportHUB-Session'];if(text(dedicated))return text(dedicated);const auth=h.authorization||h.Authorization||'',m=String(auth).match(/^Bearer\s+(.+)$/i);return m?m[1].trim():''}
async function readJson(blob,fallback,repair){try{const r=await blob.download(0),chunks=[];for await(const c of r.readableStreamBody)chunks.push(Buffer.from(c));try{const raw=Buffer.concat(chunks).toString('utf8').replace(/^\uFEFF/,'').replace(/\u0000+$/g,'').trim();return{value:raw?JSON.parse(raw):fallback,etag:r.etag||null}}catch(e){if(repair)return{value:fallback,etag:r.etag||null};throw e}}catch(e){if(e&&e.statusCode===404)return{value:fallback,etag:null};throw e}}
async function validateSession(req){const token=bearer(req);if(!token)throw error('AUTH_REQUIRED','ExportHUB-Anmeldung erforderlich.',401);const cs=connectionString();if(!cs)throw error('STORAGE_NOT_CONFIGURED','Azure-Speicher ist nicht konfiguriert.',503);const svc=BlobServiceClient.fromConnectionString(cs),container=svc.getContainerClient(TEAM_CONTAINER),authBlob=container.getBlockBlobClient(AUTH_BLOB),teamBlob=container.getBlockBlobClient(TEAM_BLOB),reads=await Promise.all([readJson(authBlob,{sessions:[]},true),readJson(teamBlob,{state:{},users:[]},false)]),sessions=Array.isArray(reads[0].value&&reads[0].value.sessions)?reads[0].value.sessions:[],hash=tokenHash(token);let session=sessions.find(s=>safeEqualText(s.tokenHash,hash));if(!session){const signed=verifySignedSessionToken(token);if(signed)session={id:text(signed.sid),userId:text(signed.uid),username:text(signed.username),expiresAt:new Date(Number(signed.exp)).toISOString(),authVersion:Number(signed.authVersion||0),mustChange:signed.mustChange===true}}
 if(!session)throw error('SESSION_INVALID','Die Sitzung ist nicht mehr gültig. Bitte erneut anmelden.',401);if(session.revokedAt||Date.parse(session.expiresAt||'')<=Date.now())throw error('SESSION_INVALID','Die Sitzung ist nicht mehr gültig. Bitte erneut anmelden.',401);const team=reads[1].value||{},users=Array.isArray(team.users)?team.users:[],user=users.find(u=>text(u.id)===text(session.userId)||usernameOf(u)===lower(session.username));if(!user||!isActive(user))throw error('ACCOUNT_DISABLED','Das Benutzerkonto ist deaktiviert.',403);if(Number(session.authVersion||0)!==Number(user.authVersion||0))throw error('SESSION_REVOKED','Die Sitzung wurde beendet. Bitte erneut anmelden.',401);if((session.mustChange||user.mustChange)===true)throw error('PASSWORD_CHANGE_REQUIRED','Vor der Nutzung muss das Startpasswort geändert werden.',403);return{user,team}}
function graphConfig(){const tenant=text(process.env.EXPORTHUB_GRAPH_TENANT_ID),clientId=text(process.env.EXPORTHUB_GRAPH_CLIENT_ID),secret=text(process.env.EXPORTHUB_GRAPH_CLIENT_SECRET);if(!tenant||!clientId||!secret||!DRIVE_USER)throw error('GRAPH_NOT_CONFIGURED','Der Microsoft-Graph-Zugriff für die Ref-Ordner ist serverseitig nicht vollständig konfiguriert.',503);return{tenant,clientId,secret}}
async function graphToken(){if(graphTokenCache&&graphTokenCache.expiresAt>Date.now()+60000)return graphTokenCache.token;const c=graphConfig(),form=new URLSearchParams({client_id:c.clientId,client_secret:c.secret,scope:'https://graph.microsoft.com/.default',grant_type:'client_credentials'}),res=await fetch('https://login.microsoftonline.com/'+encodeURIComponent(c.tenant)+'/oauth2/v2.0/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form.toString()});let data={};try{data=await res.json()}catch(_){}if(!res.ok||!data.access_token)throw error('GRAPH_AUTH_FAILED',data.error_description||'Microsoft Graph konnte nicht authentifiziert werden.',502);graphTokenCache={token:data.access_token,expiresAt:Date.now()+Math.max(300,Number(data.expires_in||3600))*1000};return graphTokenCache.token}
async function graphFetch(url,options){const token=await graphToken(),opts=Object.assign({},options||{}),headers=Object.assign({Authorization:'Bearer '+token,Accept:'application/json'},opts.headers||{});opts.headers=headers;const res=await fetch(url,opts);return res}
function encPath(path){return String(path||'').split('/').filter(Boolean).map(encodeURIComponent).join('/')}
function refValue(v){const ref=text(v).toUpperCase();if(!/^[A-Z0-9]{6}$/.test(ref))throw error('INVALID_REFERENCE','Die Sendungsreferenz ist ungültig.',400);return ref}
function folderPath(ref){return REFERENCE_FOLDER+'/'+ref}
async function listFiles(ref){const path=folderPath(ref),select='id,name,size,file,folder,createdDateTime,lastModifiedDateTime,webUrl,parentReference',first=GRAPH_BASE+'/users/'+encodeURIComponent(DRIVE_USER)+'/drive/root:/'+encPath(path)+':/children?$top=200&$select='+encodeURIComponent(select);let url=first,files=[],pages=0,folderWebUrl='';while(url&&pages<6){const res=await graphFetch(url);if(res.status===404)return{files:[],folderPath:path,folderMissing:true,folderWebUrl:''};let data={};try{data=await res.json()}catch(_){}if(!res.ok)throw error('GRAPH_LIST_FAILED',data.error&&data.error.message||('Ref-Ordner konnte nicht gelesen werden (HTTP '+res.status+').'),res.status>=500?502:res.status);for(const item of Array.isArray(data.value)?data.value:[]){if(!item||!item.file)continue;files.push({id:text(item.id),name:text(item.name)||'Dokument',size:Number(item.size||0),mimeType:text(item.file&&item.file.mimeType)||'application/octet-stream',createdDateTime:item.createdDateTime||null,lastModifiedDateTime:item.lastModifiedDateTime||null,webUrl:text(item.webUrl)});if(!folderWebUrl&&item.parentReference&&item.parentReference.path)folderWebUrl=text(item.parentReference.path)}url=data['@odata.nextLink']||'';pages++}files.sort((a,b)=>String(b.createdDateTime||b.lastModifiedDateTime||'').localeCompare(String(a.createdDateTime||a.lastModifiedDateTime||''))||a.name.localeCompare(b.name,'de'));return{files,folderPath:path,folderMissing:false,folderWebUrl}}
function disposition(name,mode){const safe=text(name).replace(/[\r\n"]/g,'_').slice(0,180)||'Dokument';return(mode==='download'?'attachment':'inline')+"; filename*=UTF-8''"+encodeURIComponent(safe)}
module.exports=async function(context,req){try{if(req.method==='OPTIONS'){context.res=json(204,{}, {Allow:'GET, OPTIONS'});return}if(req.method!=='GET'){context.res=json(405,{ok:false,code:'METHOD_NOT_ALLOWED',message:'Nur GET ist erlaubt.'},{Allow:'GET, OPTIONS'});return}await validateSession(req);const ref=refValue(req.query&&req.query.reference);let listed;try{listed=await listFiles(ref)}catch(graphError){if(graphError&&graphError.code==='GRAPH_NOT_CONFIGURED'){context.res=json(200,{ok:true,available:false,code:'GRAPH_NOT_CONFIGURED',message:graphError.message,reference:ref,folderPath:folderPath(ref),folderMissing:false,files:[]});return}throw graphError}const itemId=text(req.query&&req.query.itemId);if(!itemId){context.res=json(200,{ok:true,available:true,reference:ref,folderPath:listed.folderPath,folderMissing:listed.folderMissing,files:listed.files});return}const item=listed.files.find(f=>f.id===itemId);if(!item)throw error('FILE_NOT_FOUND','Die Datei gehört nicht zum Ref-Ordner dieser Sendung oder wurde entfernt.',404);if(Number(item.size||0)>MAX_FILE_BYTES)throw error('FILE_TOO_LARGE','Die Datei ist für die direkte ExportHUB-Ansicht zu groß.',413);const url=GRAPH_BASE+'/users/'+encodeURIComponent(DRIVE_USER)+'/drive/items/'+encodeURIComponent(item.id)+'/content',res=await graphFetch(url,{headers:{Accept:'*/*'}});if(!res.ok)throw error('GRAPH_FILE_FAILED','Die Datei konnte nicht aus dem Ref-Ordner geladen werden.',res.status>=500?502:res.status);const buffer=Buffer.from(await res.arrayBuffer()),mode=lower(req.query&&req.query.mode)==='download'?'download':'inline';context.res={status:200,headers:{'Content-Type':item.mimeType||res.headers.get('content-type')||'application/octet-stream','Content-Length':String(buffer.length),'Content-Disposition':disposition(item.name,mode),'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'},body:buffer};}catch(e){if(!(e&&e.code==='GRAPH_NOT_CONFIGURED'))context.log&&context.log.error&&context.log.error('reference-files',e&&e.code,e&&e.message);context.res=json(e.status||500,{ok:false,code:e.code||'SERVER_ERROR',message:e.message||'Ref-Ordner konnte nicht gelesen werden.'})}}
