'use strict';
const access=require('../shared/public-access-store');
const store=require('../shared/pickup-store');
const apiI18n=require('../shared/i18n');
function json(status,payload){return store.json(status,payload)}
function completeOf(record){if(typeof store.pickupComplete==='function')return store.pickupComplete(record);const expected=typeof store.expectedCollis==='function'?store.expectedCollis(record):Math.max(0,Math.round(Number(record&&record.expectedColliCount)||0)),collected=Math.max(0,Math.round(Number(record&&record.collectedPickupCollis)||0));return expected>0&&((record&&record.confirmedAt)||collected>=expected)}
module.exports=async function(context,req){
 const method=String(req&&req.method||'GET').toUpperCase();if(method==='OPTIONS'){context.res={status:204,headers:{'Cache-Control':'no-store'}};return}if(method!=='GET'&&method!=='POST'){context.res=json(405,{ok:false,code:'METHOD_NOT_ALLOWED',message:apiI18n.t(req,'api.common.getOnly')});return}
 try{const b=store.body(req)||{},q=req&&req.query||{},token=String(q.token||b.token||'').trim();const resolved=await access.resolve(req,'pickup',token,{allowUsed:false},b),accessKey=resolved.resourceKey||resolved.tokenHash,got=await store.getRecord(accessKey,resolved.environment),record=got.record||{};if(typeof store.addressFromSource==='function'&&typeof store.resolveShipmentAddress==='function'&&!store.addressFromSource(record)){try{const address=await store.resolveShipmentAddress(record,resolved.environment);if(address)record.address=address}catch(_){}}if(typeof store.resolveShipmentContainerConfig==='function'){try{const cfg=await store.resolveShipmentContainerConfig(record,resolved.environment);if(!record.transportMode&&cfg.transportMode)record.transportMode=cfg.transportMode;if(cfg.containerDocumentationRequired===true)record.containerDocumentationRequired=true}catch(_){}}if(record.status==='disabled')throw store.err('PICKUP_DISABLED',apiI18n.t(req,'api.pickup.disabled'),410);const complete=completeOf(record);context.res=json(200,Object.assign({ok:true,oneTime:false,readOnly:complete,version:'RC1014'},store.publicRecord(record,token)))}catch(e){const status=Number(e&& (e.status||e.statusCode)||0)||500;context.log&&context.log.error&&context.log.error('pickup-status RC1014',e&&e.code,e&&e.message);context.res=json(status,{ok:false,code:e.code||'PICKUP_STATUS_FAILED',message:e.message||apiI18n.t(req,'api.pickup.statusLoadFailed')})}
};