'use strict';

const crypto = require('crypto');
const auth = require('../shared/auth-store');
const CONTAINER = 'exporthub-warehouse';
const STORAGE_VERSION = '2023-11-03';
const LOCATIONS = Object.freeze({
  1: 'Regal',
  2: 'Lane 1',
  3: 'Lane 2',
  4: 'Lane 3',
  5: 'Lane 4',
  6: 'Lane 5',
  7: 'Vor dem Regal'
});
const DEFAULT_LOADERS = Object.freeze({
  '4466': 'Daniel Ollmann',
  '2050': 'Tobias',
  '2258': 'Amer',
  '7530': 'Franjo'
});
function text(v){return String(v==null?'':v).trim();}
function lower(v){return text(v).toLowerCase();}
function nowIso(){return new Date().toISOString();}
function json(status,body){return{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'},body:JSON.stringify(body)};}
function header(req,name){const h=req&&req.headers||{};const key=Object.keys(h).find(k=>lower(k)===lower(name));return key?text(h[key]):'';}
function parseBody(req){if(req&&req.body&&typeof req.body==='object'&&!Buffer.isBuffer(req.body))return req.body;const raw=Buffer.isBuffer(req&&req.body)?req.body.toString('utf8'):text(req&&(req.rawBody!=null?req.rawBody:req.body));if(!raw)return{};try{return JSON.parse(raw)}catch(_){return{}}}
function validToken(v){return /^[A-Za-z0-9_-]{6,128}$/.test(text(v));}
function tokenHash(token){return crypto.createHash('sha256').update(text(token)).digest('hex');}
function blobName(token){return 'records/'+tokenHash(token)+'.json';}
function loaderMap(){let out=Object.assign({},DEFAULT_LOADERS);const raw=text(process.env.EXPORTHUB_LOADER_PINS_JSON);if(raw){try{const x=JSON.parse(raw);if(x&&typeof x==='object'){out={};Object.keys(x).forEach(pin=>{if(/^\d{4}$/.test(pin)&&text(x[pin]))out[pin]=text(x[pin]);});}}catch(_){}}return out;}
function loaderByPin(pin){pin=text(pin).replace(/\D/g,'').slice(0,4);const name=loaderMap()[pin];return name?{pin,name}:null;}
function isGlobalAdminUser(user){const role=lower(user&&(user.role||user.rolle||user.level||user.type));const name=lower(user&&(user.name||user.user||user.login||user.username||user.displayName));const perms=Array.isArray(user&&user.permissions)?user.permissions:[];return !!(user&&(user.globalAdmin===true||user.isAdmin===true||user.admin===true||name==='tobias'||/global.?admin|administrator|admin|vollzugriff/.test(role)||perms.includes('*')));}
function tokenFromReq(req){return text(header(req,'x-exporthub-token')||header(req,'x-exporthub-session')||header(req,'authorization').replace(/^Bearer\s+/i,''));}
function requestOrigin(req){const proto=text(header(req,'x-forwarded-proto')||'https').split(',')[0],host=text(header(req,'x-forwarded-host')||header(req,'host')).split(',')[0];return host?proto+'://'+host:'';}
async function requireSession(req){const current=await auth.validateSession(req);if(!current||!current.user)throw auth.error('SESSION_INVALID','ExportHUB-Sitzung ist ungültig.',401);return current.user;}
function parseConnectionString(value){const out={};text(value).split(';').forEach(part=>{const i=part.indexOf('=');if(i>0)out[part.slice(0,i)]=part.slice(i+1);});if(!out.AccountName||!out.AccountKey)throw Object.assign(new Error('EXPORTHUB_STORAGE_CONNECTION_STRING ist nicht vollständig.'),{code:'STORAGE_CONFIG_INVALID',status:500});let endpoint=text(out.BlobEndpoint);if(!endpoint)endpoint=(out.DefaultEndpointsProtocol||'https')+'://'+out.AccountName+'.blob.'+(out.EndpointSuffix||'core.windows.net');return{account:out.AccountName,key:out.AccountKey,endpoint:endpoint.replace(/\/$/,'')};}
function storage(){return parseConnectionString(process.env.EXPORTHUB_STORAGE_CONNECTION_STRING||'');}
function encPath(name){return String(name||'').split('/').map(encodeURIComponent).join('/');}
function canonHeaders(headers){return Object.keys(headers).filter(k=>lower(k).startsWith('x-ms-')).map(k=>[lower(k),String(headers[k]).trim().replace(/\s+/g,' ')]).sort((a,b)=>a[0].localeCompare(b[0])).map(x=>x[0]+':'+x[1]+'\n').join('');}
function canonResource(account,container,blob,query){let r='/'+account+'/'+container+(blob?'/'+blob:'');const q=query||{};Object.keys(q).sort().forEach(k=>{r+='\n'+lower(k)+':'+text(q[k]);});return r;}
function sign(method,len,type,headers,blob,query){const st=storage(),n=Number(len||0)===0?'':String(len),str=[method.toUpperCase(),'','',n,'',type||'','','','','','','',canonHeaders(headers)+canonResource(st.account,CONTAINER,blob,query)].join('\n');return'SharedKey '+st.account+':'+crypto.createHmac('sha256',Buffer.from(st.key,'base64')).update(str,'utf8').digest('base64');}
async function storageRequest(method,blob,opt){opt=opt||{};const st=storage(),body=opt.body==null?null:(Buffer.isBuffer(opt.body)?opt.body:Buffer.from(String(opt.body),'utf8')),query=opt.query||{},qs=Object.keys(query).map(k=>encodeURIComponent(k)+'='+encodeURIComponent(query[k])).join('&'),url=st.endpoint+'/'+CONTAINER+(blob?'/'+encPath(blob):'')+(qs?'?'+qs:'');const headers=Object.assign({},opt.headers||{});headers['x-ms-date']=new Date().toUTCString();headers['x-ms-version']=STORAGE_VERSION;if(opt.blobType)headers['x-ms-blob-type']=opt.blobType;const ct=headers['Content-Type']||headers['content-type']||'';if(body)headers['Content-Length']=String(body.length);headers.Authorization=sign(method,body?body.length:0,ct,headers,blob,query);const res=await fetch(url,{method,headers,body});if(!res.ok&&!(opt.allow404&&res.status===404)&&!(opt.allow409&&res.status===409)){const tx=await res.text().catch(()=> '');throw Object.assign(new Error('Azure Blob Storage HTTP '+res.status+(tx?': '+tx.slice(0,220):'')),{code:'STORAGE_HTTP_'+res.status,status:500});}return res;}
async function ensureContainer(){await storageRequest('PUT','',{query:{restype:'container'},allow409:true});}
async function readRecord(token){await ensureContainer();const res=await storageRequest('GET',blobName(token),{allow404:true});if(res.status===404)return null;try{return JSON.parse(await res.text())}catch(_){return null;}}
async function writeRecord(rec){await ensureContainer();await storageRequest('PUT',blobName(rec.token),{body:JSON.stringify(rec,null,2),blobType:'BlockBlob',headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});}
function xmlDecode(s){return String(s||'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'");}
async function listRecords(){await ensureContainer();const res=await storageRequest('GET','',{query:{restype:'container',comp:'list',prefix:'records/'}}),xml=await res.text(),names=[];let m;const re=/<Name>([^<]+)<\/Name>/g;while((m=re.exec(xml)))if(/^records\/[a-f0-9]{64}\.json$/i.test(xmlDecode(m[1])))names.push(xmlDecode(m[1]));const out=[];for(const name of names){const r=await storageRequest('GET',name,{allow404:true});if(r.status===404)continue;try{const rec=JSON.parse(await r.text());if(rec&&rec.token)out.push(rec)}catch(_){}}return out;}
function safeRecord(rec,publicView){if(!rec)return null;const out={ok:true,shipmentId:rec.shipmentId||'',reference:rec.reference||'',customer:rec.customer||'',palletCount:Number(rec.palletCount||0),currentLocation:rec.currentLocation||'Eingang',locationCode:Number(rec.locationCode||0),loaderName:rec.loaderName||'',bookedAt:rec.bookedAt||'',prepared:rec.prepared===true,collected:rec.collected===true,collectedAt:rec.collectedAt||'',ready:rec.ready===true,status:rec.collected?'Abgeholt':rec.prepared?'Vorbereitet':rec.status||'',updatedAt:rec.updatedAt||'',history:Array.isArray(rec.history)?rec.history.slice(-50):[]};if(!publicView)out.token=rec.token;return out;}
function errorResponse(e){return json(Number(e&&e.status||500),{ok:false,code:text(e&&e.code)||'WAREHOUSE_ERROR',message:text(e&&e.message)||'Lagerbuchung fehlgeschlagen'});}
module.exports=async function(context,req){try{const action=lower(req.query&&req.query.action||'status'),body=parseBody(req),token=text((req.query&&req.query.token)||body.token);if(action==='status'){if(!validToken(token))return context.res=json(400,{ok:false,code:'TOKEN_INVALID',message:'Location-QR ist ungültig.'});const rec=await readRecord(token);if(!rec)return context.res=json(404,{ok:false,code:'NOT_REGISTERED',message:'Diese Sendung ist für die Lagerbuchung noch nicht registriert.'});return context.res=json(200,safeRecord(rec,true));}
if(action==='book'){if(!validToken(token))return context.res=json(400,{ok:false,code:'TOKEN_INVALID',message:'Location-QR ist ungültig.'});const pin=text(body.pin||body.loaderPin).replace(/\D/g,'').slice(0,4),loader=loaderByPin(pin),code=Math.round(Number(body.locationCode||body.location||0)),name=LOCATIONS[code];if(!loader)return context.res=json(403,{ok:false,code:'PIN_INVALID',message:'Verlader-PIN wurde nicht akzeptiert.'});if(!name)return context.res=json(400,{ok:false,code:'LOCATION_INVALID',message:'Bitte eine Location von 1 bis 7 eingeben.'});const rec=await readRecord(token);if(!rec)return context.res=json(404,{ok:false,code:'NOT_REGISTERED',message:'Sendung ist für die Lagerbuchung nicht registriert.'});if(rec.collected)return context.res=json(409,{ok:false,code:'ALREADY_COLLECTED',message:'Die Sendung wurde bereits abgeholt und kann nicht mehr umgebucht werden.'});if(rec.ready!==true&&rec.prepared!==true)return context.res=json(409,{ok:false,code:'NOT_READY',message:'Die Sendung ist noch nicht abholbereit und kann noch nicht auf eine Ausgangslocation gebucht werden.'});const stamp=nowIso(),from=rec.currentLocation||'Eingang';rec.history=Array.isArray(rec.history)?rec.history:[];rec.history.push({at:stamp,from,to:name,locationCode:code,loaderName:loader.name,type:'location'});if(rec.history.length>100)rec.history=rec.history.slice(-100);rec.currentLocation=name;rec.locationCode=code;rec.loaderName=loader.name;rec.bookedAt=stamp;rec.prepared=true;rec.status='Vorbereitet';rec.updatedAt=stamp;await writeRecord(rec);return context.res=json(200,safeRecord(rec,true));}
if(action==='move'){if(!validToken(token))return context.res=json(400,{ok:false,code:'TOKEN_INVALID',message:'Location-QR ist ungültig.'});const session=await requireSession(req);if(!auth.isAdmin(session))return context.res=json(403,{ok:false,code:'ADMIN_REQUIRED',message:'Nur Global Admin darf Sendungen manuell verschieben.'});const code=Math.round(Number(body.locationCode||body.location||0));const name=code===0?'Eingang':LOCATIONS[code];if(code<0||code>7||!name)return context.res=json(400,{ok:false,code:'LOCATION_INVALID',message:'Bitte eine Location von 0 bis 7 eingeben.'});const rec=await readRecord(token);if(!rec)return context.res=json(404,{ok:false,code:'NOT_REGISTERED',message:'Sendung ist für die Lagerbuchung nicht registriert.'});if(rec.collected)return context.res=json(409,{ok:false,code:'ALREADY_COLLECTED',message:'Die Sendung wurde bereits abgeholt und kann nicht mehr umgebucht werden.'});const stamp=nowIso(),from=rec.currentLocation||'Eingang',who=text(session.name||session.user||session.login)||'Admin';rec.history=Array.isArray(rec.history)?rec.history:[];rec.history.push({at:stamp,from,to:name,locationCode:code,loaderName:who,type:'manual'});if(rec.history.length>100)rec.history=rec.history.slice(-100);rec.currentLocation=name;rec.locationCode=code;rec.loaderName=who;rec.bookedAt=stamp;rec.prepared=code!==0;rec.status=code===0?(rec.ready?'Bereit zur Abholung':(rec.status||'Erstellt')):'Vorbereitet';rec.updatedAt=stamp;await writeRecord(rec);return context.res=json(200,safeRecord(rec,true));}
if(action==='collect'){if(!validToken(token))return context.res=json(400,{ok:false,code:'TOKEN_INVALID',message:'Location-QR ist ungültig.'});let who='ExportHUB';const pin=text(body.pin||body.loaderPin).replace(/\D/g,'').slice(0,4);if(pin){const loader=loaderByPin(pin);if(!loader)return context.res=json(403,{ok:false,code:'PIN_INVALID',message:'Verlader-PIN wurde nicht akzeptiert.'});who=loader.name}else{const u=await requireSession(req);who=text(u.name||u.user||u.login)||'ExportHUB';}const rec=await readRecord(token);if(!rec)return context.res=json(200,{ok:true,collected:true,notRegistered:true});if(!rec.collected){const stamp=nowIso(),from=rec.currentLocation||'Eingang';rec.history=Array.isArray(rec.history)?rec.history:[];rec.history.push({at:stamp,from,to:'Abgeholt',loaderName:who,type:'pickup'});rec.collected=true;rec.collectedAt=stamp;rec.collectedBy=who;rec.currentLocation='';rec.locationCode=0;rec.prepared=false;rec.status='Abgeholt';rec.updatedAt=stamp;await writeRecord(rec);}return context.res=json(200,safeRecord(rec,true));}
const session=await requireSession(req);if(action==='register'){if(!validToken(token))return context.res=json(400,{ok:false,code:'TOKEN_INVALID',message:'Location-Token fehlt.'});const existing=await readRecord(token),stamp=nowIso(),rec=existing||{schema:1,token,createdAt:stamp,history:[],currentLocation:'Eingang',locationCode:0,prepared:false,collected:false};rec.shipmentId=text(body.shipmentId||rec.shipmentId);rec.reference=text(body.reference||rec.reference).toUpperCase();rec.customer=text(body.customer||body.customerName||rec.customer);rec.palletCount=Math.max(0,Math.round(Number(body.palletCount||0)));rec.ready=body.ready===true||/bereit zur abholung|vorbereitet/i.test(text(body.status));rec.status=rec.collected?'Abgeholt':rec.prepared?'Vorbereitet':text(body.status||rec.status);rec.registeredBy=text(session.name||session.user||session.login);rec.registeredAt=stamp;rec.updatedAt=stamp;if(!rec.currentLocation&&!rec.collected)rec.currentLocation='Eingang';await writeRecord(rec);return context.res=json(200,safeRecord(rec,false));}
if(action==='list'){const list=await listRecords();return context.res=json(200,{ok:true,locations:LOCATIONS,records:list.map(r=>safeRecord(r,false))});}
return context.res=json(400,{ok:false,code:'ACTION_INVALID',message:'Unbekannte Lageraktion.'});}catch(e){context.log&&context.log.error&&context.log.error('location-booking',e);return context.res=errorResponse(e);}};
