'use strict';
const crypto=require('crypto');
const {BlobServiceClient}=require('@azure/storage-blob');

const RECORD_CONTAINER=process.env.EXPORTHUB_PICKUP_CONTAINER||'exporthub-pickup';
const POD_CONTAINER=process.env.EXPORTHUB_POD_CONTAINER||'exporthub-pod';
const TEAM_CONTAINER=process.env.EXPORTHUB_STORAGE_CONTAINER||'exporthub-data';
const TEAM_BLOB_BASE=process.env.EXPORTHUB_STORAGE_BLOB||process.env.EXPORTHUB_STATE_BLOB||'team-state.json';
const TEST_TEAM_BLOB=process.env.EXPORTHUB_TEST_STORAGE_BLOB||('testservice/'+String(TEAM_BLOB_BASE).replace(/^\/+/,''));
const MAX_RETRIES=6;

function connectionString(){return process.env.EXPORTHUB_STORAGE_CONNECTION_STRING||process.env.AzureWebJobsStorage||''}
function secret(){return process.env.EXPORTHUB_PICKUP_SECRET||process.env.EXPORTHUB_PUBLIC_ACCESS_SECRET||connectionString()||'exporthub-local-secret'}
function hash(value){return crypto.createHmac('sha256',secret()).update(String(value||'')).digest('hex')}
function safeEqualHex(a,b){try{const aa=Buffer.from(String(a||''),'hex'),bb=Buffer.from(String(b||''),'hex');return aa.length===bb.length&&aa.length>0&&crypto.timingSafeEqual(aa,bb)}catch(_){return false}}
function validToken(token){return /^[A-Za-z0-9_-]{40,160}$/.test(String(token||'').trim())}
function validAccessKey(value){return /^[a-f0-9]{64}$/i.test(String(value||''))}
function normalizeEnvironment(value){return String(value||'').toLowerCase()==='testservice'?'testservice':'production'}
function json(status,body,headers={}){return{status,headers:Object.assign({'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store, no-cache, must-revalidate','Pragma':'no-cache','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff'},headers),body:JSON.stringify(body)}}
function body(req){if(req&&req.body&&typeof req.body==='object')return req.body;try{return JSON.parse(req.body||'{}')}catch(_){return {}}}
function err(code,message,status=400){const e=new Error(message);e.code=code;e.status=status;return e}
function now(){return new Date().toISOString()}
function clone(v){return v==null?v:JSON.parse(JSON.stringify(v))}
function safeName(v){return String(v||'POD').replace(/[^a-zA-Z0-9._ -]/g,'_').replace(/\s+/g,'_').slice(0,100)}
function first(source,names){for(const name of names){const v=source&&source[name];if(v!==undefined&&v!==null&&String(v).trim()!=='')return v}return''}
function sanitizeText(v,max=180){return String(v==null?'':v).replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max)}
function positiveColliCount(value){const n=Number(value);return Number.isFinite(n)&&n>0?Math.max(0,Math.round(n)):0}
function physicalColliCount(value){const n=Number(value);return Number.isFinite(n)&&n>0?Math.max(0,Math.ceil(n)):0}
function expectedCollis(source){
 const src=source&&typeof source==='object'?source:{},lists=['rows','colli','collis','packages','packageRows','items'],rowFields=['count','qty','quantity','anzahl','menge','colliCount'],trusted=['expectedColliCount','totalCollis','totalColli','totalPackages','packagesCount','packageCount'];let best=0;
 for(const key of lists){if(!Array.isArray(src[key]))continue;let sum=0;for(const row of src[key]){let n=0;for(const f of rowFields){n=physicalColliCount(row&&row[f]);if(n>0)break}sum+=n}if(sum>best)best=sum}
 if(best>0)return best;
 for(const f of trusted){const n=positiveColliCount(src[f]);if(n>0)return n}
 for(const f of ['pickupColliCount','enteredColliCount','colliCount']){const n=positiveColliCount(src[f]);if(n>0)return n}
 return 0;
}
function teamBlobName(environment){return normalizeEnvironment(environment)==='testservice'?TEST_TEAM_BLOB:TEAM_BLOB_BASE}
function recordPath(environment,accessKey){if(!validAccessKey(accessKey))throw err('INVALID_ACCESS_KEY','Interner Pickup-Schlüssel ist ungültig.',500);return`rc995/${normalizeEnvironment(environment)}/records/${String(accessKey).toLowerCase()}.json`}
function podPrefix(environment,accessKey){return`rc995/${normalizeEnvironment(environment)}/${String(accessKey).toLowerCase()}`}
async function clients(environment='production'){
 const cs=connectionString();if(!cs)throw err('STORAGE_NOT_CONFIGURED','App-Einstellung EXPORTHUB_STORAGE_CONNECTION_STRING fehlt.',503);const service=BlobServiceClient.fromConnectionString(cs),records=service.getContainerClient(RECORD_CONTAINER),pods=service.getContainerClient(POD_CONTAINER),team=service.getContainerClient(TEAM_CONTAINER);await Promise.all([records.createIfNotExists(),pods.createIfNotExists(),team.createIfNotExists()]);return{service,records,pods,team,environment:normalizeEnvironment(environment)}
async function readBuffer(blob){const r=await blob.download(0),chunks=[];for await(const c of r.readableStreamBody)chunks.push(Buffer.from(c));return{buffer:Buffer.concat(chunks),etag:r.etag||null,contentType:r.contentType||r._response&&r._response.headers&&r._response.headers.get&&r._response.headers.get('content-type')||''}}
async function readJson(blob,fallback=null){try{const r=await readBuffer(blob);return{value:r.buffer.length?JSON.parse(r.buffer.toString('utf8')):clone(fallback),etag:r.etag}}catch(e){if(e&&e.statusCode===404)return{value:clone(fallback),etag:null};throw e}}
async function writeJson(blob,value,etag){const raw=JSON.stringify(value),conditions=etag?{ifMatch:etag}:{ifNoneMatch:'*'};return blob.upload(raw,Buffer.byteLength(raw),{blobHTTPHeaders:{blobContentType:'application/json; charset=utf-8',blobCacheControl:'no-store'},conditions})}
function recordBlob(records,accessKey,environment='production'){return records.getBlockBlobClient(recordPath(environment,accessKey))}
async function getRecord(accessKey,environment='production'){const c=await clients(environment),blob=recordBlob(c.records,accessKey,c.environment),r=await readJson(blob,null);if(!r.value)throw err('PICKUP_NOT_FOUND','Pickup-Vorgang wurde nicht gefunden.',410);return{clients:c,blob,record:r.value,etag:r.etag}}
async function mutateRecord(accessKey,environment,fn){for(let i=0;i<MAX_RETRIES;i++){const got=await getRecord(accessKey,environment),next=await fn(clone(got.record),got.clients);try{await writeJson(got.blob,next,got.etag);return next}catch(e){if(e&&e.statusCode===412&&i<MAX_RETRIES-1)continue;throw e}}throw err('CONFLICT','Datensatz konnte wegen eines Konflikts nicht gespeichert werden.',409)}
function expired(r){return!!(r&&r.expiresAt&&Date.now()>Date.parse(r.expiresAt))}
function realPodFiles(record){return(Array.isArray(record&&record.podFiles)?record.podFiles:[]).filter(f=>String(f&&f.kind||'').toLowerCase()!=='scan-confirmation')}
function signatureUrl(record,rawToken){return record&&record.signatureBlobName&&rawToken?'/api/pickup-pod?token='+encodeURIComponent(rawToken)+'&signature=1':''}
function publicRecord(r,rawToken){const files=realPodFiles(r),url=signatureUrl(r,rawToken),available=!!r.signatureBlobName,carrier=sanitizeText(first(r,['carrierName','speditionName','carrier','spedition']),180),expected=expectedCollis(r),entered=Math.max(0,Math.round(Number(first(r,['enteredColliCount','confirmedColliCount','pickupColliCount']))||0)),colliOk=r.colliCountConfirmed===true||r.colliConfirmed===true||r.pickupColliCountConfirmed===true;return{ok:true,status:r.status||'open',reference:r.reference||'',customer:r.customer||'',recipient:r.recipient||'',address:r.address||'',locationName:r.locationName||'',shipmentId:r.shipmentId||'',palletOut:Math.max(0,Number(r.palletOut||0)||0),carrierName:carrier,speditionName:carrier,carrier,spedition:carrier,expectedColliCount:expected,colliCount:expected,totalColli:expected,packageCount:expected,enteredColliCount:entered,colliCountConfirmed:colliOk,colliConfirmed:colliOk,pickupColliCountConfirmed:colliOk,createdAt:r.createdAt||null,expiresAt:r.expiresAt||null,confirmedAt:r.confirmedAt||null,driverName:r.driverName||'',pickupDriverName:r.driverName||'',licensePlate:r.licensePlate||'',vehicleLicensePlate:r.licensePlate||'',kennzeichen:r.licensePlate||'',loaderName:r.loaderName||'',loadedBy:r.loaderName||'',loader:r.loaderName||'',verlader:r.loaderName||'',signatureAvailable:available,driverSignatureAvailable:available,signatureStored:available,driverSignatureUrl:url,pickupSignatureUrl:url,podType:available?'signed-loadlist':'',podStatus:available?'POD vorhanden':'Unterschrift fehlt',podCount:(available?1:0)+files.length,podFiles:files.map(f=>({id:f.id,name:f.name,type:f.type,size:f.size,uploadedAt:f.uploadedAt,kind:f.kind||'',url:rawToken?'/api/pickup-pod?token='+encodeURIComponent(rawToken)+'&file='+encodeURIComponent(f.id):''}))}}
function parseSignature(dataUrl){const value=String(dataUrl||''),m=value.match(/^data:image\/(jpeg|jpg|png|webp);base64,([A-Za-z0-9+/=\s]+)$/i);if(!m)throw err('SIGNATURE_REQUIRED','Die digitale Unterschrift ist Pflicht.',400);const type=m[1].toLowerCase()==='jpg'?'jpeg':m[1].toLowerCase(),buffer=Buffer.from(m[2].replace(/\s+/g,''),'base64');if(buffer.length<100)throw err('INVALID_SIGNATURE','Die digitale Unterschrift ist leer oder ungültig.',400);if(buffer.length>2*1024*1024)throw err('SIGNATURE_TOO_LARGE','Die digitale Unterschrift ist zu groß.',413);return{buffer,type:'image/'+type,extension:type==='jpeg'?'jpg':type}}
async function saveDriverSignature(c,record,dataUrl){if(!record||!validAccessKey(record.accessKey))throw err('INVALID_ACCESS_KEY','Interner Pickup-Schlüssel fehlt.',500);const parsed=parseSignature(dataUrl),blobName=podPrefix(c.environment,record.accessKey)+'/driver-signature.'+parsed.extension,blob=c.pods.getBlockBlobClient(blobName);await blob.uploadData(parsed.buffer,{overwrite:true,blobHTTPHeaders:{blobContentType:parsed.type,blobCacheControl:'no-store'},metadata:{accesshash:String(record.accessKey),reference:String(record.reference||''),kind:'driver-signature'}});return{signatureBlobName:blobName,signatureType:parsed.type,signatureSize:parsed.buffer.length,signatureStoredAt:now()}}
async function updateTeam(record,podsToAdd=[],rawToken=''){
 const c=await clients(record.environment),blob=c.team.getBlockBlobClient(teamBlobName(c.environment));
 for(let i=0;i<MAX_RETRIES;i++){
  const d=await readJson(blob,null),doc=d.value||{schemaVersion:3,revision:0,state:{},users:[]};doc.state=doc.state||{};doc.state.shipments=Array.isArray(doc.state.shipments)?doc.state.shipments:[];doc.state.tasks=Array.isArray(doc.state.tasks)?doc.state.tasks:[];
  const ref=String(record.reference||'').trim().toUpperCase(),sid=String(record.shipmentId||'').trim(),sigUrl=signatureUrl(record,rawToken),hasSignature=!!record.signatureBlobName,sh=doc.state.shipments.find(x=>(sid&&String(x.id||x.shipmentId||'')===sid)||(ref&&String(x.ref||x.reference||'').trim().toUpperCase()===ref));
  if(sh){const iso=record.confirmedAt||now(),day=iso.slice(0,10),dt=new Date(iso);sh.actualPickupDate=day;sh.pickedUpAtDate=day;sh.actualPickupTime=isNaN(dt)?'':dt.toLocaleTimeString('de-DE',{timeZone:'Europe/Berlin',hour:'2-digit',minute:'2-digit',second:'2-digit'});sh.pickedUpAt=iso;sh.pickupConfirmedAt=iso;sh.qrPickupConfirmedAt=iso;sh.pickupStatus='abgeholt';sh.pickupQrUsed=true;sh.pickupQrUsedAt=iso;sh.qrPickupConfirmed=true;sh.status=hasSignature?'POD vorhanden':'Abgeholt';sh.processStatus=sh.status;sh._syncUpdatedAt=iso;sh._syncDeviceId='qr-pickup';sh.pickupDriverName=record.driverName||'';sh.driverName=record.driverName||'';sh.pickupLicensePlate=record.licensePlate||'';sh.licensePlate=record.licensePlate||'';sh.vehicleLicensePlate=record.licensePlate||'';sh.kennzeichen=record.licensePlate||'';sh.loaderName=record.loaderName||'';sh.loadedBy=record.loaderName||'';sh.loader=record.loaderName||'';sh.verlader=record.loaderName||'';const carrier=sanitizeText(first(record,['carrierName','speditionName','carrier','spedition']),180),expected=expectedCollis(record),entered=Math.max(0,Math.round(Number(first(record,['enteredColliCount','confirmedColliCount','pickupColliCount']))||0));if(carrier){sh.carrier=carrier;sh.carrierName=carrier;sh.spedition=carrier;sh.speditionName=carrier}sh.expectedColliCount=expected;sh.pickupColliCount=expected;sh.enteredColliCount=entered;sh.colliCountConfirmed=true;sh.pickupColliCountConfirmed=true;sh.driverSignatureUrl=sigUrl;sh.pickupDriverSignatureUrl=sigUrl;sh.signatureAvailable=hasSignature;sh.podAvailable=hasSignature;sh.podConfirmed=hasSignature;sh.podStatus=hasSignature?'POD vorhanden':'Unterschrift fehlt';sh.podFiles=(Array.isArray(sh.podFiles)?sh.podFiles:[]).filter(x=>String(x&&x.kind||'').toLowerCase()!=='scan-confirmation');if(Array.isArray(podsToAdd)&&podsToAdd.length&&rawToken){for(const p of podsToAdd){if(!p||String(p.kind||'').toLowerCase()==='scan-confirmation')continue;const url='/api/pickup-pod?token='+encodeURIComponent(rawToken)+'&file='+encodeURIComponent(p.id);if(!sh.podFiles.some(x=>x.remoteId===p.id||x.url===url))sh.podFiles.push({id:'QR-'+p.id,name:p.name,filename:p.name,url,uploadedAt:p.uploadedAt,remote:true,remoteId:p.id,mimeType:p.type,type:p.type,size:p.size,source:'QR',kind:p.kind||''})}}sh.podCount=(hasSignature?1:0)+sh.podFiles.length}
  for(const t of doc.state.tasks){if(String(t.area||'').toLowerCase()==='abholtag'&&((sid&&String(t.linkedShipmentId||'')===sid)||(ref&&String(t.linkedShipmentRef||'').toUpperCase()===ref))){t.status='erledigt';t.done=true;t.doneAt=record.confirmedAt||now();t.completedAt=t.doneAt;t._syncUpdatedAt=t.doneAt;t._syncDeviceId='qr-pickup'}}
  doc.revision=Number(doc.revision||0)+1;doc.updatedAt=now();doc.updatedBy='QR-Abholscan';doc.updatedByDevice='qr-pickup';doc.clientVersion='RC995';try{await writeJson(blob,doc,d.etag);return doc}catch(e){if(e&&e.statusCode===412&&i<MAX_RETRIES-1)continue;throw e}
 }
}

module.exports={RECORD_CONTAINER,POD_CONTAINER,TEAM_CONTAINER,TEAM_BLOB_BASE,TEST_TEAM_BLOB,clients,connectionString,hash,safeEqualHex,validToken,validAccessKey,normalizeEnvironment,json,body,err,now,clone,readBuffer,readJson,writeJson,recordBlob,getRecord,mutateRecord,expired,publicRecord,updateTeam,safeName,parseSignature,saveDriverSignature,signatureUrl,realPodFiles,first,sanitizeText,expectedCollis,teamBlobName,podPrefix};
