'use strict';

const crypto = require('crypto');
const auth = require('../shared/auth-store');

const CONTAINER = 'exporthub-releases';
const MANIFEST_BLOB = 'manifest.json';
const STORAGE_VERSION = '2023-11-03';
const GH_OWNER = process.env.EXPORTHUB_GITHUB_OWNER || 'Deadshot89';
const GH_REPO = process.env.EXPORTHUB_GITHUB_REPO || 'ExportHub';
const GH_BRANCH = process.env.EXPORTHUB_GITHUB_BRANCH || 'main';
const GH_PATH = process.env.EXPORTHUB_GITHUB_PATH || 'index.html';
const GH_TOKEN = process.env.EXPORTHUB_GITHUB_TOKEN || '';
const GH_DISCOVER_LIMIT = Math.max(5, Math.min(30, Number(process.env.EXPORTHUB_GITHUB_RELEASE_LIMIT || 14)));
const GH_SYNC_TTL_MS = 30000;

function text(v){return String(v==null?'':v).trim();}
function lower(v){return text(v).toLowerCase();}
function nowIso(){return new Date().toISOString();}
function safeVersion(v){const m=text(v).toUpperCase().match(/^RC(\d{1,7})$/);return m?'RC'+m[1]:'';}
function versionNum(v){const m=safeVersion(v).match(/\d+/);return m?Number(m[0]):0;}
function json(status,body){return{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'},body:JSON.stringify(body)};}
function parseBody(req){if(req&&req.body&&typeof req.body==='object'&&!Buffer.isBuffer(req.body))return req.body;const raw=Buffer.isBuffer(req&&req.body)?req.body.toString('utf8'):text(req&&(req.rawBody!=null?req.rawBody:req.body));if(!raw)return{};try{return JSON.parse(raw)}catch(_){return{}}}
function detectVersion(html){const s=String(html||'');let m=s.match(/version\s*:\s*['\"](RC\d+)['\"]/i);if(!m)m=s.match(/data-exporthub-version\s*=\s*['\"](RC\d+)['\"]/i);if(!m)m=s.match(/Aktuelle Version\s+(RC\d+)/i);return safeVersion(m&&m[1]);}
function decodeJsString(s){return String(s||'').replace(/\\'/g,"'").replace(/\\\"/g,'\"').replace(/\\n/g,' ').replace(/\\r/g,' ').replace(/\\t/g,' ').replace(/\\\\/g,'\\').trim();}
function extractArrayStrings(source,key){const re=new RegExp(key+'\\s*:\\s*(?:Object\\.freeze\\()?\\s*\\[([\\s\\S]*?)\\]\\s*\\)?','i'),m=String(source||'').match(re);if(!m)return[];const out=[],r=/(['\"])((?:\\.|(?!\1)[\s\S])*?)\1/g;let x;while((x=r.exec(m[1]))&&out.length<12){const v=decodeJsString(x[2]);if(v)out.push(v)}return out;}
function releaseMeta(html,commitMessage){const s=String(html||''),meta=s.match(/<script\b[^>]*\bid=['"]rc514-github-release-metadata['"][^>]*>([\s\S]*?)<\/script>/i);if(meta){try{const d=JSON.parse(meta[1]);return{title:text(d&&d.title)||text(commitMessage).split(/\r?\n/)[0],changes:Array.isArray(d&&d.changes)?d.changes.map(text).filter(Boolean).slice(0,12):[],tests:Array.isArray(d&&d.tests)?d.tests.map(text).filter(Boolean).slice(0,12):[]}}catch(_){}}const titleMatch=s.match(/title\s*:\s*(['"])((?:\.|(?!\1)[\s\S])*?)\1/i);return{title:titleMatch?decodeJsString(titleMatch[2]):text(commitMessage).split(/\r?\n/)[0],changes:extractArrayStrings(s,'changes'),tests:extractArrayStrings(s,'tests')};}
function validateInlineScripts(html){const source=String(html||''),re=/<script\b([^>]*)>([\s\S]*?)<\/script>/gi;let match,count=0;while((match=re.exec(source))){const attrs=String(match[1]||'');if(/\bsrc\s*=/.test(attrs))continue;const type=attrs.match(/\btype\s*=\s*['\"]([^'\"]+)['\"]/i);if(type&&!/javascript|ecmascript|module/i.test(type[1]))continue;const code=String(match[2]||'').trim();if(!code)continue;count++;try{new Function(code)}catch(err){const e=new Error('JavaScript-Syntaxfehler in Script '+count+': '+text(err&&err.message));e.code='HTML_SCRIPT_SYNTAX';e.status=400;throw e}}return count;}
async function requireAdmin(req){const current=await auth.validateSession(req);if(!current||!current.user||!auth.isAdmin(current.user))throw auth.error('ADMIN_REQUIRED','Nur globale Administratoren dürfen Testversionen und Releases verwalten.',403);return current.user;}
function userLabel(u){return text(u&&(u.name||u.user||u.login||u.username))||'Global Admin';}
function parseConnectionString(value){const out={};text(value).split(';').forEach(part=>{const i=part.indexOf('=');if(i>0)out[part.slice(0,i)]=part.slice(i+1);});if(!out.AccountName||!out.AccountKey)throw Object.assign(new Error('EXPORTHUB_STORAGE_CONNECTION_STRING ist nicht vollständig.'),{code:'STORAGE_CONFIG_INVALID',status:500});let endpoint=text(out.BlobEndpoint);if(!endpoint)endpoint=(out.DefaultEndpointsProtocol||'https')+'://'+out.AccountName+'.blob.'+(out.EndpointSuffix||'core.windows.net');return{account:out.AccountName,key:out.AccountKey,endpoint:endpoint.replace(/\/$/,'')};}
function storage(){return parseConnectionString(process.env.EXPORTHUB_STORAGE_CONNECTION_STRING||'');}
function encPath(name){return String(name||'').split('/').map(encodeURIComponent).join('/');}
function canonHeaders(headers){return Object.keys(headers).filter(k=>lower(k).startsWith('x-ms-')).map(k=>[lower(k),String(headers[k]).trim().replace(/\s+/g,' ')]).sort((a,b)=>a[0].localeCompare(b[0])).map(x=>x[0]+':'+x[1]+'\n').join('');}
function canonResource(account,container,blob,query){let r='/'+account+'/'+container+(blob?'/'+blob:'');Object.keys(query||{}).sort().forEach(k=>{r+='\n'+lower(k)+':'+text(query[k])});return r;}
function sign(method,len,type,headers,blob,query){const st=storage(),n=Number(len||0)===0?'':String(len),str=[method.toUpperCase(),'','',n,'',type||'','','','','','','',canonHeaders(headers)+canonResource(st.account,CONTAINER,blob,query)].join('\n');return'SharedKey '+st.account+':'+crypto.createHmac('sha256',Buffer.from(st.key,'base64')).update(str,'utf8').digest('base64');}
async function storageRequest(method,blob,opt){opt=opt||{};const st=storage(),body=opt.body==null?null:(Buffer.isBuffer(opt.body)?opt.body:Buffer.from(String(opt.body),'utf8')),query=opt.query||{},qs=Object.keys(query).map(k=>encodeURIComponent(k)+'='+encodeURIComponent(query[k])).join('&'),url=st.endpoint+'/'+CONTAINER+(blob?'/'+encPath(blob):'')+(qs?'?'+qs:'');const headers=Object.assign({},opt.headers||{});headers['x-ms-date']=new Date().toUTCString();headers['x-ms-version']=STORAGE_VERSION;if(opt.blobType)headers['x-ms-blob-type']=opt.blobType;const ct=headers['Content-Type']||headers['content-type']||'';if(body)headers['Content-Length']=String(body.length);headers.Authorization=sign(method,body?body.length:0,ct,headers,blob,query);const res=await fetch(url,{method,headers,body});if(!res.ok&&!(opt.allow404&&res.status===404)&&!(opt.allow409&&res.status===409)){const tx=await res.text().catch(()=> '');throw Object.assign(new Error('Azure Blob Storage HTTP '+res.status+(tx?': '+tx.slice(0,220):'')),{code:'STORAGE_HTTP_'+res.status,status:500})}return res;}
async function ensureContainer(){await storageRequest('PUT','',{query:{restype:'container'},allow409:true});}
async function readBlob(name,allowMissing){const r=await storageRequest('GET',name,{allow404:!!allowMissing});if(r.status===404)return null;return Buffer.from(await r.arrayBuffer());}
async function writeBlob(name,body,type){const b=Buffer.isBuffer(body)?body:Buffer.from(String(body),'utf8');await storageRequest('PUT',name,{body:b,blobType:'BlockBlob',headers:{'Content-Type':type||'application/octet-stream','Cache-Control':'no-store'}});}
function emptyManifest(){return{schema:2,production:null,test:null,previousProduction:null,updatedAt:null,lastGithubSync:null,githubError:null,releases:[]};}
async function loadManifest(){await ensureContainer();const b=await readBlob(MANIFEST_BLOB,true);if(!b)return emptyManifest();try{const m=Object.assign(emptyManifest(),JSON.parse(b.toString('utf8'))||{});m.releases=Array.isArray(m.releases)?m.releases:[];return m}catch(_){return emptyManifest()}}
async function saveManifest(m){m.schema=2;m.updatedAt=nowIso();await writeBlob(MANIFEST_BLOB,JSON.stringify(m,null,2),'application/json; charset=utf-8');}
function releaseByVersion(m,v){v=safeVersion(v);return(m.releases||[]).find(r=>safeVersion(r.version)===v)||null;}
function ghHeaders(){const h={'Accept':'application/vnd.github+json','User-Agent':'ExportHUB-Release-Center','X-GitHub-Api-Version':'2022-11-28'};if(GH_TOKEN)h.Authorization='Bearer '+GH_TOKEN;return h;}
async function ghJson(url){const r=await fetch(url,{headers:ghHeaders(),cache:'no-store'}),t=await r.text();if(!r.ok)throw Object.assign(new Error('GitHub API HTTP '+r.status+(t?': '+t.slice(0,180):'')),{code:'GITHUB_HTTP_'+r.status,status:502});try{return JSON.parse(t)}catch(_){throw Object.assign(new Error('GitHub API lieferte ungültiges JSON.'),{code:'GITHUB_INVALID_JSON',status:502})}}
function rawUrl(sha){return'https://raw.githubusercontent.com/'+encodeURIComponent(GH_OWNER)+'/'+encodeURIComponent(GH_REPO)+'/'+encodeURIComponent(sha)+'/'+GH_PATH.split('/').map(encodeURIComponent).join('/');}
async function ghHtml(sha){const r=await fetch(rawUrl(sha),{headers:GH_TOKEN?{Authorization:'Bearer '+GH_TOKEN,'User-Agent':'ExportHUB-Release-Center'}:{'User-Agent':'ExportHUB-Release-Center'},cache:'no-store'});if(!r.ok)throw Object.assign(new Error('GitHub-Datei HTTP '+r.status+' für '+String(sha).slice(0,7)),{code:'GITHUB_FILE_'+r.status,status:502});return Buffer.from(await r.arrayBuffer());}
function githubInfo(){return{owner:GH_OWNER,repo:GH_REPO,branch:GH_BRANCH,path:GH_PATH};}
async function cacheGithubHtml(sha,buf){const blob='github-cache/'+sha+'.html';const existing=await readBlob(blob,true);if(!existing)await writeBlob(blob,buf,'text/html; charset=utf-8');return blob;}
async function syncGithub(m,force){const last=Date.parse(m.lastGithubSync||'')||0;if(!force&&Date.now()-last<GH_SYNC_TTL_MS)return{changed:false,skipped:true};let changed=false;try{const url='https://api.github.com/repos/'+encodeURIComponent(GH_OWNER)+'/'+encodeURIComponent(GH_REPO)+'/commits?sha='+encodeURIComponent(GH_BRANCH)+'&path='+encodeURIComponent(GH_PATH)+'&per_page=100';const commits=await ghJson(url);if(!Array.isArray(commits))throw new Error('GitHub Commit-Liste fehlt.');let candidates=commits.slice(0,GH_DISCOVER_LIMIT).map(c=>{const msg=text(c&&c.commit&&c.commit.message),mv=msg.match(/\bRC\s*(\d{1,7})\b/i);return{c,msg,hint:mv?'RC'+mv[1]:''}});const seen=new Set();for(const x of candidates){const sha=text(x.c.sha);if(!sha)continue;let buf,html,detected='';try{buf=await ghHtml(sha);if(!buf||buf.length<1000)continue;html=buf.toString('utf8');detected=detectVersion(html)||safeVersion(x.hint)}catch(_){continue}if(!detected||seen.has(detected))continue;seen.add(detected);let r=releaseByVersion(m,detected);if(r&&r.githubSha===sha&&Number(r.size||0)>0)continue;validateInlineScripts(html);const meta=releaseMeta(html,x.msg),blob=await cacheGithubHtml(sha,buf),commit=x.c.commit||{},author=commit.author||{},committer=commit.committer||{};if(!r){r={version:detected,testedAt:null,testedBy:null,promotedAt:null,promotedBy:null};m.releases.push(r)}Object.assign(r,{source:'github',githubSha:sha,githubShortSha:sha.slice(0,7),githubBlob:blob,githubUrl:'https://github.com/'+GH_OWNER+'/'+GH_REPO+'/commit/'+sha,commitMessage:x.msg.split(/\r?\n/)[0],committedAt:text(committer.date||author.date),githubAuthor:text(author.name),size:buf.length,sha256:crypto.createHash('sha256').update(buf).digest('hex'),title:meta.title||detected,changes:meta.changes,tests:meta.tests,discoveredAt:r.discoveredAt||nowIso()});changed=true}m.lastGithubSync=nowIso();m.githubError=null;if(changed||force)await saveManifest(m);else await saveManifest(m);return{changed,skipped:false,count:candidates.length}}catch(e){m.lastGithubSync=nowIso();m.githubError=text(e.message);await saveManifest(m);if(force)throw e;return{changed:false,error:e}}}
async function releaseHtml(r){if(!r)throw Object.assign(new Error('Release nicht gefunden.'),{code:'RELEASE_NOT_FOUND',status:404});if(r.githubSha){const blob=r.githubBlob||('github-cache/'+r.githubSha+'.html');let b=await readBlob(blob,true);if(!b){b=await ghHtml(r.githubSha);await cacheGithubHtml(r.githubSha,b)}return b}if(r.blob){return await readBlob(r.blob,false)}throw Object.assign(new Error(r.version+' besitzt keine ladbare GitHub-Version.'),{code:'RELEASE_NO_SOURCE',status:404});}
function exposedReleases(m){const keep=new Set([safeVersion(m.production),safeVersion(m.test),safeVersion(m.previousProduction)].filter(Boolean));return(m.releases||[]).filter(r=>r.githubSha||keep.has(safeVersion(r.version))).sort((a,b)=>versionNum(b.version)-versionNum(a.version));}
function publicManifest(m){return{ok:true,schema:2,production:safeVersion(m.production)||null,test:safeVersion(m.test)||null,previousProduction:safeVersion(m.previousProduction)||null,updatedAt:m.updatedAt||null,github:Object.assign(githubInfo(),{lastSync:m.lastGithubSync||null,error:m.githubError||null}),releases:exposedReleases(m).map(r=>({version:safeVersion(r.version),source:r.githubSha?'github':'legacy',githubSha:r.githubSha||'',githubShortSha:r.githubShortSha||'',githubUrl:r.githubUrl||'',commitMessage:r.commitMessage||'',committedAt:r.committedAt||r.uploadedAt||'',githubAuthor:r.githubAuthor||r.uploadedBy||'',uploadedAt:r.committedAt||r.uploadedAt||'',uploadedBy:r.githubAuthor||r.uploadedBy||'GitHub',size:Number(r.size||0),sha256:r.sha256||'',title:r.title||r.commitMessage||safeVersion(r.version),changes:Array.isArray(r.changes)?r.changes:[],tests:Array.isArray(r.tests)?r.tests:[],testedAt:r.testedAt||null,testedBy:r.testedBy||null,promotedAt:r.promotedAt||null,promotedBy:r.promotedBy||null}))};}
function err(e){return json(Number(e&&e.status||500),{ok:false,code:text(e&&e.code)||'RELEASE_ERROR',message:text(e&&e.message)||'Release-Fehler'});}

module.exports=async function(context,req){try{const action=lower(req.query&&req.query.action||'active'),channel=lower(req.query&&req.query.channel||'production'),body=parseBody(req);
  if(action==='active'){let m=await loadManifest();let v=safeVersion(channel==='test'?m.test:m.production),r=releaseByVersion(m,v);if(v&&!r){await syncGithub(m,true).catch(()=>{});m=await loadManifest();r=releaseByVersion(m,v)}return context.res=json(200,{ok:true,channel,version:v||null,size:r&&Number(r.size||0)||0,source:r&&r.githubSha?'github':'legacy',sha:r&&r.githubShortSha||'',title:r&&r.title||'',changes:r&&r.changes||[]})}
  if(action==='html'){let m=await loadManifest(),v=safeVersion(channel==='test'?m.test:m.production),r=releaseByVersion(m,v);if(!v)return context.res=json(404,{ok:false,code:'NO_ACTIVE_RELEASE',message:'Für '+channel+' ist noch keine RC aktiviert.'});if(!r){await syncGithub(m,true).catch(()=>{});m=await loadManifest();r=releaseByVersion(m,v)}const b=await releaseHtml(r);return context.res={status:200,isRaw:true,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store, no-cache, must-revalidate','X-ExportHUB-Release':v,'X-ExportHUB-Channel':channel,'X-ExportHUB-Source':r&&r.githubSha?'github':'legacy'},body:b}}
  const admin=await requireAdmin(req),who=userLabel(admin);
  if(action==='list'){let m=await loadManifest();await syncGithub(m,false);m=await loadManifest();return context.res=json(200,publicManifest(m))}
  if(action==='sync-github'){let m=await loadManifest();await syncGithub(m,true);m=await loadManifest();return context.res=json(200,publicManifest(m))}
  if(action==='upload'||action==='seed-production')return context.res=json(410,{ok:false,code:'GITHUB_ONLY',message:'RC-Dateien werden nicht mehr im Testportal hochgeladen. Neue Versionen bitte als index.html nach GitHub pushen; das Release-Center übernimmt sie automatisch.'});
  if(action==='set-test'){let m=await loadManifest(),v=safeVersion(body.version);if(!releaseByVersion(m,v)){await syncGithub(m,true);m=await loadManifest()}const r=releaseByVersion(m,v);if(!r||!r.githubSha)return context.res=json(404,{ok:false,code:'GITHUB_RELEASE_NOT_FOUND',message:v+' wurde in der GitHub-Historie nicht gefunden.'});m.test=v;await saveManifest(m);return context.res=json(200,{ok:true,test:v,title:r.title||'',changes:r.changes||[],sha:r.githubShortSha||''})}
  if(action==='mark-tested'){const m=await loadManifest(),v=safeVersion(body.version),r=releaseByVersion(m,v);if(!r)return context.res=json(404,{ok:false,code:'RELEASE_NOT_FOUND',message:v+' wurde nicht gefunden.'});if(safeVersion(m.test)!==v)return context.res=json(409,{ok:false,code:'NOT_ACTIVE_TEST',message:'Nur die aktive Testversion kann bestätigt werden.'});r.testedAt=nowIso();r.testedBy=who;await saveManifest(m);return context.res=json(200,{ok:true,version:v,testedAt:r.testedAt})}
  if(action==='promote'){const m=await loadManifest(),v=safeVersion(body.version),r=releaseByVersion(m,v);if(!r)return context.res=json(404,{ok:false,code:'RELEASE_NOT_FOUND',message:v+' wurde nicht gefunden.'});if(safeVersion(m.test)!==v)return context.res=json(409,{ok:false,code:'NOT_ACTIVE_TEST',message:'Nur die aktive Testversion kann freigegeben werden.'});if(!r.testedAt)return context.res=json(409,{ok:false,code:'TEST_REQUIRED',message:v+' muss zuerst als getestet markiert werden.'});if(safeVersion(m.production)!==v)m.previousProduction=safeVersion(m.production)||m.previousProduction||null;m.production=v;r.promotedAt=nowIso();r.promotedBy=who;await saveManifest(m);return context.res=json(200,{ok:true,production:v,previousProduction:m.previousProduction})}
  if(action==='rollback'){const m=await loadManifest(),prev=safeVersion(m.previousProduction),r=releaseByVersion(m,prev);if(!prev||!r)return context.res=json(409,{ok:false,code:'NO_ROLLBACK',message:'Keine gültige Rollback-Version vorhanden.'});const cur=safeVersion(m.production);m.production=prev;m.previousProduction=cur||null;await saveManifest(m);return context.res=json(200,{ok:true,production:m.production,previousProduction:m.previousProduction})}
  return context.res=json(400,{ok:false,code:'ACTION_INVALID',message:'Unbekannte Release-Aktion.'});
}catch(e){context.log&&context.log.error&&context.log.error('exporthub-release',e);context.res=err(e)}};
