'use strict';
const access=require('../shared/public-access-store');
const store=require('../shared/pickup-store');
const apiI18n=require('../shared/i18n');
function json(status,body){return store.json(status,body)}
function text(v){return String(v==null?'':v).trim()}
module.exports=async function(context,req){
 if(req.method==='OPTIONS'){context.res={status:204,headers:{Allow:'GET, OPTIONS','Cache-Control':'no-store'},body:''};return}if(req.method!=='GET'){context.res=json(405,{ok:false,code:'METHOD_NOT_ALLOWED',message:apiI18n.t(req,'api.common.getOnly')});return}
 try{const token=text(req.query&&req.query.token),resolved=await access.resolve(req,'pickup',token,{allowUsed:true},req.query||{}),accessKey=resolved.resourceKey||resolved.tokenHash,got=await store.getRecord(accessKey,resolved.environment),rec=got.record||{},wantSignature=String(req.query&&req.query.signature||'')==='1'||!text(req.query&&req.query.file),fileId=text(req.query&&req.query.file),history=typeof store.pickupHistory==='function'?store.pickupHistory(rec):(Array.isArray(rec.pickupHistory)?rec.pickupHistory:[]),complete=typeof store.pickupComplete==='function'?store.pickupComplete(rec):!!rec.confirmedAt;if(!complete&&!history.length)throw store.err('PICKUP_NOT_CONFIRMED',apiI18n.t(req,'api.pod.notConfirmed'),409);if(!wantSignature&&!complete)throw store.err('PICKUP_NOT_CONFIRMED',apiI18n.t(req,'api.pod.documentsNotConfirmed'),409);let blobName='',fallbackType='application/octet-stream';if(wantSignature){blobName=text(rec.signatureBlobName);fallbackType=text(rec.signatureType)||'image/jpeg';if(!blobName)throw store.err('SIGNATURE_NOT_FOUND',apiI18n.t(req,'api.pod.signatureNotFound'),404)}else{const files=Array.isArray(rec.podFiles)?rec.podFiles:[],f=files.find(x=>text(x&&x.id)===fileId||text(x&&x.remoteId)===fileId);if(!f)throw store.err('POD_FILE_NOT_FOUND',apiI18n.t(req,'api.pod.fileNotFound'),404);blobName=text(f.blobName||f.storageBlobName||f.path||f.storagePath);fallbackType=text(f.type||f.mimeType)||'application/pdf';if(!blobName)throw store.err('POD_FILE_NOT_STORED',apiI18n.t(req,'api.pod.fileNotStored'),404)}const blob=got.clients.pods.getBlobClient(blobName);let read;try{read=await store.readBuffer(blob)}catch(e){if(e&&e.statusCode===404)throw store.err(wantSignature?'SIGNATURE_NOT_FOUND':'POD_FILE_NOT_FOUND',wantSignature?apiI18n.t(req,'api.pod.signatureStorageMissing'):apiI18n.t(req,'api.pod.fileStorageMissing'),404);throw e}context.res={status:200,headers:{'Content-Type':text(read.contentType)||fallbackType,'Content-Length':String(read.buffer.length),'Cache-Control':'private, no-store, no-cache, must-revalidate','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff'},isRaw:true,body:read.buffer}}catch(e){context.log&&context.log.error&&context.log.error('pickup-pod RC995',e&&e.code,e&&e.message);context.res=json(e.status||e.statusCode||500,{ok:false,code:e.code||'SERVER_ERROR',message:e.message||apiI18n.t(req,'api.pod.loadFailed')})}
};
