'use strict';
const {BlobServiceClient}=require('@azure/storage-blob');
const access=require('../shared/public-access-store');
const auth=require('../shared/auth-store');

const TEAM_CONTAINER=process.env.EXPORTHUB_STORAGE_CONTAINER||process.env.EXPORTHUB_CONTAINER||'exporthub-data';
const TEAM_BLOB_BASE=process.env.EXPORTHUB_STORAGE_BLOB||process.env.EXPORTHUB_STATE_BLOB||'team-state.json';
const TEST_TEAM_BLOB=process.env.EXPORTHUB_TEST_STORAGE_BLOB||('testservice/'+String(TEAM_BLOB_BASE).replace(/^\/+/,''));
const MAX_RETRIES=8;
function text(v){return String(v==null?'':v).trim()}
function lower(v){return text(v).toLowerCase()}
function upper(v){return text(v).toUpperCase()}
function arr(v){return Array.isArray(v)?v:[]}
function obj(v){return!!v&&typeof v==='object'&&!Array.isArray(v)}
function num(v){const n=Number(String(v==null?'':v).replace(',','.'));return Number.isFinite(n)?n:0}
function now(){return new Date().toISOString()}
function error(code,message,status=400){const e=new Error(message);e.code=code;e.status=status;return e}
function json(status,body,headers={}){return access.json(status,body,headers)}
function body(req){return access.body(req)}
function connectionString(){return process.env.EXPORTHUB_STORAGE_CONNECTION_STRING||process.env.AzureWebJobsStorage||''}
function wait(ms){return new Promise(r=>setTimeout(r,ms))}
function isConflict(e){return!!(e&&(Number(e.statusCode||e.status)===412||['ConditionNotMet','TargetConditionNotMet'].includes(String(e.code||''))))}
function teamBlobName(environment){return environment==='testservice'?TEST_TEAM_BLOB:TEAM_BLOB_BASE}
async function teamBlob(environment){const cs=connectionString();if(!cs)throw error('STORAGE_NOT_CONFIGURED','Azure-Speicher ist nicht konfiguriert.',503);const c=BlobServiceClient.fromConnectionString(cs).getContainerClient(TEAM_CONTAINER);await c.createIfNotExists();return c.getBlockBlobClient(teamBlobName(environment))}
async function readTeam(blob){try{const r=await blob.download(0),chunks=[];for await(const c of r.readableStreamBody)chunks.push(Buffer.from(c));const raw=Buffer.concat(chunks).toString('utf8').replace(/^\uFEFF/,'').trim();return{value:raw?JSON.parse(raw):{schemaVersion:3,revision:0,state:{}},etag:r.etag||null}}catch(e){if(e&&e.statusCode===404)return{value:{schemaVersion:3,revision:0,state:{}},etag:null};throw e}}
async function writeTeam(blob,value,etag){const raw=JSON.stringify(value);return blob.upload(raw,Buffer.byteLength(raw),{blobHTTPHeaders:{blobContentType:'application/json; charset=utf-8',blobCacheControl:'no-store'},conditions:etag?{ifMatch:etag}:{ifNoneMatch:'*'}})}
function sid(sh){return text(sh&&(sh.id||sh.shipmentId||sh.uuid||sh.ref||sh.reference))}
function sref(sh){return upper(sh&&(sh.ref||sh.reference||sh.shipmentRef||sh.referenceNumber||sh.id||sh.shipmentId))}
function sameShipment(sh,subjectId,reference){const i=text(subjectId),r=upper(reference);return!!((i&&sid(sh)===i)||(r&&sref(sh)===r))}
function shipmentCopies(state){const out=[];function add(v){if(obj(v)&&out.indexOf(v)<0)out.push(v)}['shipments','savedShipments','shipmentArchive','archivedShipments'].forEach(k=>arr(state&&state[k]).forEach(add));['shipment','currentShipment','selectedShipment'].forEach(k=>add(state&&state[k]));return out}
function findCopies(state,subjectId,reference){return shipmentCopies(state).filter(sh=>sameShipment(sh,subjectId,reference))}
function stamp(sh){const n=Date.parse(text(sh&&(sh._syncUpdatedAt||sh.updatedAt||sh.modifiedAt||sh.createdAt)));return Number.isFinite(n)?n:0}
function findShipment(state,subjectId,reference){return findCopies(state,subjectId,reference).sort((a,b)=>stamp(b)-stamp(a))[0]||null}
function avisEnabled(sh){return!!(sh&&(sh.customerAvisEnabled===true||sh.avisEnabled===true))}
function rowsOf(sh){const lists=[sh&&sh.rows,sh&&sh.colli,sh&&sh.collis,sh&&sh.packages,sh&&sh.packagingRows].filter(Array.isArray).sort((a,b)=>b.length-a.length);return lists[0]||[]}
function dateTimeOf(sh){return text(sh&&(sh.pickupConfirmedAt||sh.qrPickupConfirmedAt||sh.pickupCompletedAt||sh.pickedUpAt||sh.actualPickupAt||sh.actualPickupDate||sh.podServerVerifiedAt))}
function pickupCarrierOf(sh){return text(sh&&(sh.pickupCarrierName||sh.pickupSpeditionName||sh.carrierName||sh.speditionName||sh.carrier||sh.spedition))}
function pickupPlateOf(sh){return text(sh&&(sh.pickupLicensePlate||sh.licensePlate||sh.vehicleLicensePlate||sh.kennzeichen))}
function pickupDriverOf(sh){return text(sh&&(sh.pickupDriverName||sh.driverName||sh.confirmedBy))}
function publicStatus(sh){const raw=text(sh&&(sh.status||sh.processStatus||sh.pickupStatus));if(/abgeholt|picked/i.test(raw)||dateTimeOf(sh))return'Abgeholt';return raw||'Erstellt'}
function fileName(f,fallback){return text(f&&(f.name||f.filename||f.fileName||f.title||f.label))||fallback||'Dokument'}
function fileMime(f){return text(f&&(f.mimeType||f.contentType||f.type))||'application/octet-stream'}
function fileSource(f){return text(f&&(f.data||f.dataUrl||f.content||f.url||f.downloadUrl||f.href||f.contentUrl))}
function safeExternalUrl(raw){try{const u=new URL(raw);if(u.protocol!=='https:')return'';const h=u.hostname.toLowerCase();if(/(^|\.)sharepoint\.com$/.test(h)||/(^|\.)blob\.core\.windows\.net$/.test(h)||h==='1drv.ms')return u.href;return''}catch(_){return''}}
function parseDataUrl(raw,mimeHint){if(!/^data:/i.test(raw))return null;const p=raw.indexOf(',');if(p<0)return null;const meta=raw.slice(5,p),payload=raw.slice(p+1),parts=meta.split(';'),mime=text(parts[0])||mimeHint||'application/octet-stream',is64=parts.some(x=>lower(x)==='base64');try{return{mime,bytes:is64?Buffer.from(payload,'base64'):Buffer.from(decodeURIComponent(payload),'utf8')}}catch(_){return null}}
function documentRecords(sh){
 const out=[],seen=new Set(),lists=[['deliveryFiles','Lieferschein'],['deliveryNotesFiles','Lieferschein'],['lieferscheine','Lieferschein'],['podFiles','POD']];
 lists.forEach(([key,category])=>arr(sh&&sh[key]).forEach((f,i)=>{if(!obj(f)||f.placeholder||f.fallback||f.customerAvisVisible===false)return;const source=fileSource(f);if(!source)return;const name=fileName(f,category+' '+(i+1)),id=text(f.id||f.remoteId)||Buffer.from(key+'|'+name+'|'+i).toString('base64url').slice(0,80),uniq=category+'|'+id;if(seen.has(uniq))return;seen.add(uniq);const inline=parseDataUrl(source,fileMime(f)),external=inline?'':safeExternalUrl(source);if(!inline&&!external)return;out.push({id,name,mime:fileMime(f),size:Number(f.size||inline&&inline.bytes.length||0)||0,category,inline,external})}));
 arr(sh&&sh.documents).forEach((f,i)=>{if(!obj(f)||f.customerAvisVisible!==true)return;const source=fileSource(f);if(!source)return;const name=fileName(f,'Dokument '+(i+1)),id=text(f.id)||Buffer.from('doc|'+name+'|'+i).toString('base64url').slice(0,80),inline=parseDataUrl(source,fileMime(f)),external=inline?'':safeExternalUrl(source);if(inline||external)out.push({id,name,mime:fileMime(f),size:Number(f.size||inline&&inline.bytes.length||0)||0,category:text(f.category)||'Dokument',inline,external})});return out
}
function podAvailable(sh){return!!(sh&&(sh.podAvailable===true||sh.podConfirmed===true||sh.signatureAvailable===true||documentRecords(sh).some(d=>d.category==='POD')))}
function contentDisposition(name){return'attachment; filename*=UTF-8\'\''+encodeURIComponent(fileName({name},'Dokument'))}
function publicShipment(sh,session){
 const actual=dateTimeOf(sh),docs=documentRecords(sh).map(d=>({id:d.id,name:d.name,mime:d.mime,size:d.size,category:d.category,downloadUrl:'/api/customer-avis?action=document&id='+encodeURIComponent(d.id)+'&session='+encodeURIComponent(session)})),podDocs=docs.filter(d=>d.category==='POD');
 if(actual)return{ok:true,closed:true,status:'Abgeholt',reference:sref(sh),actualPickupAt:actual,pickup:{carrier:pickupCarrierOf(sh),licensePlate:pickupPlateOf(sh),driverName:pickupDriverOf(sh)},documents:[],pod:{available:podAvailable(sh),status:text(sh.podStatus)||(podAvailable(sh)?'POD vorhanden':'Noch nicht vorhanden'),documents:podDocs},avis:{enabled:true,closed:true,singleUse:true,session:true},lastUpdatedAt:text(sh.updatedAt||sh._syncUpdatedAt||sh.modifiedAt)};
 const rows=rowsOf(sh).map((r,i)=>({position:i+1,type:text(r.type||r.packaging||r.verpackung),count:Math.max(0,Math.round(num(r.count||r.qty||r.quantity||r.anzahl))),weight:num(r.weight||r.gewicht),ldm:num(r.ldm||r.loadingMeter),length:num(r.l||r.length),width:num(r.w||r.width),height:num(r.h||r.height)})),totals=rows.reduce((a,r)=>{a.count+=r.count;a.weight+=r.weight;a.ldm+=r.count*r.ldm;return a},{count:0,weight:0,ldm:0}),planned=text(sh.customerAvisPickupDate||sh.avisPickupDate||sh.plannedPickupDate||sh.pickupDate),from=text(sh.customerAvisPickupTimeFrom||sh.avisPickupTimeFrom),to=text(sh.customerAvisPickupTimeTo||sh.avisPickupTimeTo);
 return{ok:true,closed:false,reference:sref(sh),shipmentId:sid(sh),sender:{name:text(sh.senderName||(sh.sender&&sh.sender.name))||'Essentra Components GmbH',address:text(sh.senderAddress||(sh.sender&&[sh.sender.street,sh.sender.city,sh.sender.country].filter(Boolean).join(', ')))||'Montel-Allee 3, 41334 Nettetal, Deutschland'},customerName:text(sh.customerName||(sh.customer&&sh.customer.name)),customerNumber:text(sh.customerNumber||sh.customerAccount||sh.customerNo),customerReference:text(sh.customerReference||sh.customerRef||sh.orderReference||sh.purchaseOrder||sh.poNumber),salesOrder:text(sh.salesOrder||sh.salesOrderNumber||sh.orderNumber),recipientName:text(sh.recipientName||sh.destinationName||sh.customerName),recipientAddress:text(sh.recipientAddress||sh.deliveryAddress||sh.destinationAddress),country:text(sh.recipientCountry||sh.country),shipDate:text(sh.shipDate||sh.shippingDate||sh.shipmentDate||sh.dispatchDate),incoterm:text(sh.incoterm||sh.incoterms),carrier:text(sh.carrier||sh.carrierName||sh.spedition),status:publicStatus(sh),goodsDescription:text(sh.goodsDescription||sh.description||sh.warenbeschreibung),rows,totals,documents:docs,appointment:{date:planned,timeFrom:from,timeTo:to,plate:text(sh.customerAvisPickupPlate||sh.avisPickupPlate),shipmentNumber:text(sh.customerAvisShipmentNumber||sh.avisShipmentNumber),note:text(sh.customerAvisPickupNote||sh.avisPickupNote),submittedAt:text(sh.customerAvisResponseAt||sh.avisResponseAt)},actualPickupAt:'',pod:{available:podAvailable(sh),status:text(sh.podStatus)||(podAvailable(sh)?'POD vorhanden':'Noch nicht vorhanden'),documents:podDocs},avis:{enabled:true,singleUse:true,session:true,securityVersion:995},lastUpdatedAt:text(sh.updatedAt||sh._syncUpdatedAt||sh.modifiedAt)}
}
function validateTime(v){return!v||/^([01]\d|2[0-3]):[0-5]\d$/.test(v)}
function validateAppointment(payload){const date=text(payload.pickupDate),from=text(payload.timeFrom),to=text(payload.timeTo),plate=text(payload.plate).replace(/[\r\n]+/g,' ').slice(0,40),shipmentNumber=text(payload.shipmentNumber).replace(/[\r\n]+/g,' ').slice(0,120);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw error('PICKUP_DATE_REQUIRED','Bitte ein gültiges Abholdatum angeben.',400);if(!validateTime(from)||!validateTime(to))throw error('TIME_INVALID','Bitte eine gültige Abholzeit angeben.',400);if(!shipmentNumber)throw error('SHIPMENT_NUMBER_REQUIRED','Bitte die Sendungsnummer angeben.',400);return{date,from,to,plate,shipmentNumber,note:text(payload.note).slice(0,1000)}}
function applyAppointment(state,target,payload){const v=validateAppointment(payload),stamp=now(),values={customerAvisPickupDate:v.date,avisPickupDate:v.date,customerAvisPickupTimeFrom:v.from,avisPickupTimeFrom:v.from,customerAvisPickupTimeTo:v.to,avisPickupTimeTo:v.to,customerAvisPickupPlate:v.plate,avisPickupPlate:v.plate,customerAvisShipmentNumber:v.shipmentNumber,avisShipmentNumber:v.shipmentNumber,customerAvisPickupNote:v.note,avisPickupNote:v.note,customerAvisResponseAt:stamp,avisResponseAt:stamp,customerAvisResponseReference:sref(target),avisResponseReference:sref(target),customerAvisResponseStatus:'bestätigt',avisResponseStatus:'bestätigt',customerConfirmed:true,customerConfirmedAt:stamp,customerConfirmedVia:'customer-avis',plannedPickupDate:v.date,pickupDate:v.date,updatedAt:stamp,_syncUpdatedAt:stamp};findCopies(state,sid(target),sref(target)).forEach(sh=>Object.assign(sh,values));return values}
async function setAvisFlags(blob,subjectId,reference,enabled,actor){for(let i=0;i<MAX_RETRIES;i++){const d=await readTeam(blob),team=d.value||{},state=obj(team.state)?team.state:{},copies=findCopies(state,subjectId,reference);if(!copies.length)throw error('SHIPMENT_NOT_FOUND','Sendung wurde nicht gefunden.',404);const stamp=now(),values=enabled?{customerAvisEnabled:true,avisEnabled:true,customerAvisEnabledAt:stamp,avisEnabledAt:stamp,customerAvisSecurityVersion:995,avisSecurityVersion:995,customerAvisDisabledAt:'',avisDisabledAt:'',updatedAt:stamp,_syncUpdatedAt:stamp}:{customerAvisEnabled:false,avisEnabled:false,customerAvisDisabledAt:stamp,avisDisabledAt:stamp,customerAvisSecurityVersion:0,avisSecurityVersion:0,updatedAt:stamp,_syncUpdatedAt:stamp};copies.forEach(sh=>Object.assign(sh,values));team.state=state;team.revision=Number(team.revision||0)+1;team.updatedAt=stamp;team.updatedBy=actor||'Kunden-Avis';team.updatedByUserId='customer-avis';team.clientVersion='RC995';try{await writeTeam(blob,team,d.etag);return findShipment(state,subjectId,reference)}catch(e){if(isConflict(e)&&i<MAX_RETRIES-1){await wait(60+i*80);continue}throw e}}throw error('STATE_CONFLICT','Kunden-Avis konnte nicht gespeichert werden.',409)}
async function saveAppointment(blob,sessionInfo,session,payload){for(let i=0;i<MAX_RETRIES;i++){const d=await readTeam(blob),team=d.value||{},state=obj(team.state)?team.state:{},target=findShipment(state,sessionInfo.record.subjectId,sessionInfo.record.reference);if(!target||!avisEnabled(target))throw error('AVIS_DISABLED','Dieser Kunden-Avis ist nicht mehr aktiv.',410);if(dateTimeOf(target))throw error('AVIS_CLOSED','Der Lieferavis ist nach der Abholung geschlossen. Änderungen sind nicht mehr möglich.',410);applyAppointment(state,target,payload);team.state=state;team.revision=Number(team.revision||0)+1;team.updatedAt=now();team.updatedBy='Kunden-Avis';team.updatedByUserId='customer-avis';team.clientVersion='RC995';try{await writeTeam(blob,team,d.etag);return publicShipment(findShipment(state,sessionInfo.record.subjectId,sessionInfo.record.reference),session)}catch(e){if(isConflict(e)&&i<MAX_RETRIES-1){await wait(80+i*100);continue}throw e}}throw error('STATE_CONFLICT','Avis-Bestätigung konnte nicht gespeichert werden.',409)}
function sessionFromRequest(req,payload){const h=req&&req.headers||{};return text(h['x-exporthub-avis-session']||h['X-ExportHUB-Avis-Session']||(payload&&payload.session)||(req&&req.query&&req.query.session))}
module.exports=async function(context,req){
 if(req.method==='OPTIONS'){context.res={status:204,headers:{'Cache-Control':'no-store','Allow':'GET, POST, OPTIONS','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY','X-Content-Type-Options':'nosniff'},body:''};return}
 try{
  const payload=body(req),action=lower(payload.action);
  if(req.method==='POST'&&(action==='issue'||action==='disable')){
   const internal=await auth.validateSession(req);if(!auth.hasAnyEditRight(internal.user))throw auth.error('WRITE_FORBIDDEN','Für Kunden-Avis fehlen Bearbeitungsrechte.',403);const env=access.environment(req,payload),blob=await teamBlob(env),d=await readTeam(blob),state=obj(d.value&&d.value.state)?d.value.state:{},subjectId=text(payload.shipmentId||payload.id||payload.reference||payload.ref),reference=upper(payload.reference||payload.ref),target=findShipment(state,subjectId,reference);if(!target)throw error('SHIPMENT_NOT_FOUND','Sendung wurde nicht gefunden.',404);const actualSubject=sid(target)||subjectId,actualRef=sref(target);
   if(action==='disable'){await access.revokeSubject(req,'avis',actualSubject,'disabled',internal.user.name||internal.user.user||'ExportHUB',payload);await setAvisFlags(blob,actualSubject,actualRef,false,internal.user.name||internal.user.user);context.res=json(200,{ok:true,disabled:true,shipmentId:actualSubject,reference:actualRef,version:'RC995'});return}
   await setAvisFlags(blob,actualSubject,actualRef,true,internal.user.name||internal.user.user);const issued=await access.issue(req,'avis',{subjectId:actualSubject,shipmentId:actualSubject,reference:actualRef,actor:internal.user.name||internal.user.user||'ExportHUB'},7*86400000,payload);context.res=json(200,{ok:true,issued:true,token:issued.token,shipmentId:actualSubject,reference:actualRef,expiresAt:issued.expiresAt,url:'/customer-avis.html?token='+encodeURIComponent(issued.token),oneTime:true,version:'RC995'});return
  }
  if(req.method==='POST'&&action==='authorize'){
   const raw=text(payload.token),resolved=await access.resolve(req,'avis',raw,{allowUsed:false},payload),blob=await teamBlob(resolved.environment),d=await readTeam(blob),state=obj(d.value&&d.value.state)?d.value.state:{},sh=findShipment(state,resolved.record.subjectId,resolved.record.reference),reference=upper(payload.reference);if(!sh||!avisEnabled(sh))throw error('AVIS_DISABLED','Dieser Kunden-Avis-Link ist nicht mehr aktiv.',410);if(!reference||reference!==sref(sh)){const failed=await access.registerFailure(resolved.environment,'avis',resolved.tokenHash,'reference');if(failed.lockedUntil)throw error('ACCESS_LOCKED','Zu viele falsche Referenzeingaben. Der Zugriff ist vorübergehend gesperrt.',429);await wait(300);throw error('AVIS_ACCESS_DENIED','Die Referenznummer ist nicht korrekt.',403)}await access.clearFailures(resolved.environment,'avis',resolved.tokenHash);const consumed=await access.consume(resolved.environment,'avis',resolved.tokenHash,{reason:'authorized'}),sessionInfo=access.issueSession(consumed),response=publicShipment(sh,sessionInfo.session);response.session=sessionInfo.session;response.sessionExpiresAt=sessionInfo.expiresAt;response.rawLinkConsumed=true;context.res=json(200,response);return
  }
  const session=sessionFromRequest(req,payload);if(!session)throw error('AVIS_SESSION_REQUIRED','Bitte den Kunden-Avis-Link erneut öffnen.',401);const sessionInfo=await access.resolveSession(session,'avis'),blob=await teamBlob(sessionInfo.environment),d=await readTeam(blob),state=obj(d.value&&d.value.state)?d.value.state:{},sh=findShipment(state,sessionInfo.record.subjectId,sessionInfo.record.reference);if(!sh||!avisEnabled(sh))throw error('AVIS_DISABLED','Dieser Kunden-Avis ist nicht mehr aktiv.',410);
  if(req.method==='GET'){
   const getAction=lower(req.query&&req.query.action);if(getAction==='document'){const id=text(req.query&&req.query.id),doc=documentRecords(sh).find(x=>x.id===id);if(!doc)throw error('DOCUMENT_NOT_FOUND','Das Dokument ist nicht mehr verfügbar.',404);if(dateTimeOf(sh)&&doc.category!=='POD')throw error('AVIS_CLOSED','Nach der Abholung ist nur noch der POD verfügbar.',410);if(doc.inline){context.res={status:200,isRaw:true,headers:{'Content-Type':doc.inline.mime||doc.mime||'application/octet-stream','Content-Disposition':contentDisposition(doc.name),'Cache-Control':'private, no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff'},body:doc.inline.bytes};return}if(doc.external){context.res={status:302,headers:{Location:doc.external,'Cache-Control':'no-store','Referrer-Policy':'no-referrer'},body:''};return}throw error('DOCUMENT_NOT_FOUND','Das Dokument ist nicht mehr verfügbar.',404)}context.res=json(200,publicShipment(sh,session));return
  }
  if(req.method==='POST'){const postAction=lower(payload.action||'appointment');if(postAction!=='appointment')throw error('UNKNOWN_ACTION','Unbekannte Avis-Aktion.',400);context.res=json(200,await saveAppointment(blob,sessionInfo,session,payload));return}
  context.res=json(405,{ok:false,code:'METHOD_NOT_ALLOWED'},{Allow:'GET, POST, OPTIONS'});
 }catch(e){context.log&&context.log.error&&context.log.error('customer-avis RC995',e&&e.code,e&&e.message);context.res=json(e.status||e.statusCode||500,{ok:false,code:e.code||'SERVER_ERROR',message:e.message||'Kunden-Avis ist vorübergehend nicht verfügbar.'})}
};
