'use strict';
const fs=require('fs');
const path='index.html';
let src=fs.readFileSync(path,'utf8');
if(src.includes('var rc1017SubShipmentQrRuntime=Object.create(null);')){
  console.log('RC1017 task7 already applied');
  process.exit(0);
}
function replaceOne(from,to,label){
  const count=src.split(from).length-1;
  if(count!==1)throw new Error((label||'anchor')+' expected once, found '+count);
  src=src.replace(from,to);
}

const oldRender=`function renderRc1017SubShipments(result){
 var card=document.getElementById('rc380StowPlan'),count=Math.max(1,num(result&&result.requiredTruckCount||shipment().requiredTruckCount||1));
 if(card){card.setAttribute('data-rc1017-truck-count',String(count));card.setAttribute('data-rc1017-multi-truck',count>1?'1':'0')}
 return count
}`;
const newRender=`var rc1017SubShipmentQrRuntime=Object.create(null);
function rc1017SubShipment(main,subShipmentId){return arr(main&&main.subShipments).find(function(item){return q(item&&item.subShipmentId)===q(subShipmentId)})||null}
function rc1017RowsForSubShipment(main,subShipmentId){var sub=arr(main&&main.subShipments).find(function(item){return q(item&&item.subShipmentId)===q(subShipmentId)});return sub?arr(sub.rows).map(function(row){return copy(row)}):[]}
function rc1017SubSequence(sub){return Math.max(1,Math.round(num(sub&&(sub.subShipmentSequence||sub.sequence))||1))}
function rc1017SubTotal(main,sub){return Math.max(1,Math.round(num(sub&&(sub.subShipmentTotal||sub.total))||arr(main&&main.subShipments).length||1))}
function rc1017SubLabel(main,sub){var sequence=rc1017SubSequence(sub),total=rc1017SubTotal(main,sub);return q(sub&&(sub.subShipmentLabel||sub.label))||('Sendung '+sequence+' von '+total)}
function rc1017SubStarted(sub){return!!(sub&&(sub.locked===true||/partial|confirmed|picked|abgeholt|pod|completed|abgeschlossen|teilweise/.test(low(sub.status))))}
function rc1017SubPicked(sub){return!!(sub&&/confirmed|picked|abgeholt|pod|completed|abgeschlossen/.test(low(sub.status)))}
function rc1017SubMetrics(main,sub){var rows=rc1017RowsForSubShipment(main,sub&&sub.subShipmentId),colli=rows.reduce(function(n,r){return n+Math.max(0,Math.round(num(r.count)))},0),weight=rows.reduce(function(n,r){return n+Math.max(0,num(r.weight))},0),ldm=rows.reduce(function(n,r){return n+Math.max(0,num(r.count))*Math.max(0,num(r.ldm))},0);return{rows:rows,colli:colli,weight:weight,ldm:ldm}}
function rc1017SubShipmentProgressText(main){var subs=arr(main&&main.subShipments),picked=subs.filter(rc1017SubPicked).length;return subs.length>1?(subs.length+' Teilsendungen · '+picked+' von '+subs.length+' abgeholt'):''}
function rc1017SubShipmentDocumentShipment(main,subShipmentId){
 main=main||currentSaved()||shipment();var sub=rc1017SubShipment(main,subShipmentId);if(!sub)return null;var temp=copy(main),metrics=rc1017SubMetrics(main,sub),sequence=rc1017SubSequence(sub),total=rc1017SubTotal(main,sub),label=rc1017SubLabel(main,sub),parentRef=refOf(main),runtime=rc1017SubShipmentQrRuntime[q(subShipmentId)]||null;
 temp.rows=copy(metrics.rows);temp.colli=copy(metrics.rows);temp.collis=copy(metrics.rows);temp.packages=copy(metrics.rows);temp.totalColli=metrics.colli;temp.totalWeight=metrics.weight;temp.subShipmentId=q(sub.subShipmentId);temp.subShipmentSequence=sequence;temp.subShipmentTotal=total;temp.subShipmentLabel=label;temp.rc1017ParentReference=parentRef;temp.rc1017SubShipmentDocument=true;temp.rc1017KeepQrInPdf=true;temp.status=q(sub.status)||q(main.status);temp.processStatus=temp.status;temp.comments=['Hauptreferenz: '+parentRef,label,q(main.comments)].filter(Boolean).join(' · ');
 ['pickupToken','pickupQrToken','qrToken','publicPickupToken','publicAccessToken','pickupQrRegisteredAt','pickupQrActivationStartedAt'].forEach(function(key){try{delete temp[key]}catch(_){temp[key]=''}});temp.pickupQrRegistered=false;
 var history=arr(sub.pickupHistory),last=history.length?history[history.length-1]:null;if(last){temp.pickupDriverName=q(last.driverName);temp.driverName=q(last.driverName);temp.pickupLicensePlate=q(last.licensePlate);temp.licensePlate=q(last.licensePlate);temp.pickupLoaderName=q(last.loaderName);temp.loaderName=q(last.loaderName);temp.pickupConfirmedAt=q(last.confirmedAt)}
 if(runtime&&q(runtime.token)){temp.pickupToken=q(runtime.token);temp.pickupQrToken=q(runtime.token);temp.pickupQrRegistered=true;temp.pickupQrRegisteredAt=q(runtime.registeredAt)||new Date().toISOString();temp.pickupQrEnvironment=q(runtime.environment);temp.environment=q(runtime.environment)||temp.environment}
 return temp
}
function rc1017EuroPallets(rows){return arr(rows).reduce(function(total,row){return /euro.*pal|eur.*pal/i.test(q(row&&(row.type||row.packaging||row.verpackung)))?total+Math.max(0,Math.round(num(row.count))):total},0)}
async function rc1017ActivateSubShipmentQr(subShipmentId,button){
 var main=currentSaved()||shipment(),sub=rc1017SubShipment(main,subShipmentId);if(!main||!sub){alert('Teilsendung wurde nicht gefunden.');return false}var key=q(sub.subShipmentId),existing=rc1017SubShipmentQrRuntime[key];if(existing&&q(existing.token)){renderRc1017SubShipments({requiredTruckCount:arr(main.subShipments).length,subShipments:main.subShipments});return existing}if(rc1017SubStarted(sub)){alert('Die Teilsendung ist bereits in Verwendung. Ein neuer QR-Code wird nach begonnener Abholung nicht erzeugt.');return false}
 var metrics=rc1017SubMetrics(main,sub),sequence=rc1017SubSequence(sub),total=rc1017SubTotal(main,sub),old=q(button&&button.textContent);if(button){button.disabled=true;button.textContent='QR wird erstellt …'}
 try{var payload={shipmentId:q(main.id||main.shipmentId||refOf(main)),id:q(main.id||main.shipmentId||refOf(main)),reference:refOf(main),ref:refOf(main),customerName:q(main.customerName||main.customer&&main.customer.name),recipient:q(main.recipient||main.recipientName),recipientAddress:q(main.recipientAddress||main.deliveryAddress||main.destinationAddress),locationName:q(main.locationName),carrierName:q(main.carrierName||main.carrier||main.speditionName),palletOut:rc1017EuroPallets(metrics.rows),plannedPickupDate:q(main.plannedPickupDate||main.pickupDate),subShipmentId:key,subShipmentSequence:sequence,subShipmentTotal:total,rows:copy(metrics.rows)},response=await fetch('/api/pickup-init',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({shipment:payload})}),data={};try{data=await response.json()}catch(_){data={}}if(!response.ok||data.ok===false)throw new Error(q(data.message)||('QR-Registrierung HTTP '+response.status));if(!q(data.token))throw new Error('Der Server hat keinen QR-Token zurückgegeben.');rc1017SubShipmentQrRuntime[key]={token:q(data.token),environment:q(data.environment),registeredAt:new Date().toISOString(),status:q(data.status)||'open'};renderRc1017SubShipments({requiredTruckCount:arr(main.subShipments).length,subShipments:main.subShipments});return rc1017SubShipmentQrRuntime[key]}catch(e){console.error('RC1017 Teilsendungs-QR',e);alert('QR-Code für '+rc1017SubLabel(main,sub)+' konnte nicht erstellt werden: '+q(e&&e.message||e));return false}finally{if(button){button.disabled=false;button.textContent=old||'QR-Code'}}
}
async function rc1017PrintSubShipment(subShipmentId,button){var main=currentSaved()||shipment(),sub=rc1017SubShipment(main,subShipmentId);if(!sub)return false,varRuntime=false;var runtime=rc1017SubShipmentQrRuntime[q(subShipmentId)];if(!runtime||!q(runtime.token)){runtime=await rc1017ActivateSubShipmentQr(subShipmentId,button);if(!runtime)return false;varRuntime=true}var temp=rc1017SubShipmentDocumentShipment(main,subShipmentId),download=window.__EXPORTHUB_RC1017_DOWNLOAD_SUBSHIPMENT__;if(!temp||typeof download!=='function'){alert('Die Teilsendungs-Ladeliste ist noch nicht verfügbar.');return false}var name=('Ladeliste_'+refOf(main)+'_'+rc1017SubSequence(sub)+'-von-'+rc1017SubTotal(main,sub)+'.pdf').replace(/[^A-Za-z0-9._-]+/g,'_');try{await download(temp,name);return false}catch(e){console.error('RC1017 Teilsendungs-Ladeliste',e);alert('Ladeliste konnte nicht erstellt werden: '+q(e&&e.message||e));return false}}
function rc1017PrintSubShipmentStow(subShipmentId){var main=currentSaved()||shipment(),sub=rc1017SubShipment(main,subShipmentId);if(!sub)return false;var rows=rc1017RowsForSubShipment(main,subShipmentId),plan=buildStowPlan(rows,currentStowVehicle()),label=rc1017SubLabel(main,sub),vehicle=currentStowVehicle(),bands=arr(plan.rows).map(function(row){var left=Math.max(0,(num(row.startCm)/Math.max(1,num(plan.vehicleLength)))*100),width=Math.max(1,(num(row.depth)/Math.max(1,num(plan.vehicleLength)))*100),steps=arr(row.placements).map(function(p){return 'Schritt '+num(p.step)+' · '+q(p.type)}).join(' / ');return '<div style="position:absolute;left:'+left+'%;width:'+width+'%;top:8px;bottom:8px;border:1px solid #2563eb;border-radius:8px;background:#dbeafe;padding:6px;overflow:hidden;font-size:10px"><b>R'+num(row.no)+'</b><br>'+esc(steps)+'</div>'}).join(''),list=arr(plan.rows).map(function(row){return '<tr><td>R'+num(row.no)+'</td><td>'+esc(fmtM(row.startCm))+'–'+esc(fmtM(row.endCm))+'</td><td>'+arr(row.placements).map(function(p){return esc('Schritt '+num(p.step)+' · '+q(p.type))}).join('<br>')+'</td></tr>'}).join(''),html='<!doctype html><html lang="de"><head><meta charset="utf-8"><title>Stauplan '+esc(refOf(main))+' · '+esc(label)+'</title><style>@page{size:A4 landscape;margin:10mm}body{font-family:Segoe UI,Arial,sans-serif;color:#0f172a}h1{color:#08245d;margin:0 0 4px}.meta{margin:0 0 14px;color:#475569}.truck{position:relative;height:180px;border:3px solid #0f172a;border-radius:12px;background:#f8fafc;margin:12px 0}.axis{display:flex;justify-content:space-between;font-size:11px;font-weight:700}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #cbd5e1;padding:6px;text-align:left;vertical-align:top;font-size:11px}th{background:#e2e8f0}</style></head><body><h1>Stauplan · '+esc(label)+'</h1><p class="meta">Hauptreferenz: '+esc(refOf(main))+' · '+esc(vehicle.label)+' · '+num(plan.totalUnits)+' physische Collis</p><div class="axis"><span>Vorne / Stirnwand</span><span>Hinten / Türen</span></div><div class="truck">'+bands+'</div><table><thead><tr><th>Reihe</th><th>Position</th><th>Beladereihenfolge</th></tr></thead><tbody>'+list+'</tbody></table></body></html>',w=window.open('about:blank','_blank','width=1200,height=820');if(!w){alert('Das Druckfenster wurde vom Browser blockiert.');return false}try{w.opener=null;w.document.open();w.document.write(html);w.document.close();var run=function(){try{w.focus();w.print()}catch(e){console.error('RC1017 Stauplan drucken',e)}};if(w.document.readyState==='complete')setTimeout(run,250);else w.addEventListener('load',function(){setTimeout(run,200)},{once:true});return false}catch(e){try{w.close()}catch(_){}alert('Der Stauplan konnte nicht geöffnet werden: '+q(e&&e.message||e));return false}}
function renderRc1017SubShipments(result){
 var main=shipment(),card=document.getElementById('rc380StowPlan'),count=Math.max(1,num(result&&result.requiredTruckCount||main.requiredTruckCount||1)),subs=arr(result&&result.subShipments&&result.subShipments.length?result.subShipments:main.subShipments),existing=card&&card.querySelector('#rc1017-subshipments');if(existing)existing.remove();
 if(card){card.setAttribute('data-rc1017-truck-count',String(count));card.setAttribute('data-rc1017-multi-truck',count>1?'1':'0')}if(!card||count<=1||subs.length<2)return count;
 var picked=subs.filter(rc1017SubPicked).length,section=document.createElement('section');section.id='rc1017-subshipments';section.style.cssText='margin-top:16px;padding-top:16px;border-top:2px solid #dbeafe';section.innerHTML='<div style="display:flex;justify-content:space-between;align-items:flex-start;gap:12px;flex-wrap:wrap"><div><span class="pill blue">'+count+' LKW erforderlich</span><h3 style="margin:7px 0 3px">Teilsendungen</h3><div class="muted">Jeder LKW hat einen eigenen QR-Code, eine eigene Ladeliste und einen eigenen Stauplan.</div></div><span class="pill gray">'+picked+' von '+subs.length+' abgeholt</span></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:10px;margin-top:12px">'+subs.map(function(sub){var sequence=rc1017SubSequence(sub),total=rc1017SubTotal(main,sub),label='Sendung '+sequence+' von '+total,metrics=rc1017SubMetrics(main,sub),runtime=rc1017SubShipmentQrRuntime[q(sub.subShipmentId)],started=rc1017SubStarted(sub),pickedUp=rc1017SubPicked(sub),qr='',temp=null;if(runtime&&q(runtime.token)&&window.ExportHUBPickupPOD&&typeof window.ExportHUBPickupPOD.qrMarkup==='function'){try{temp=rc1017SubShipmentDocumentShipment(main,sub.subShipmentId);qr=window.ExportHUBPickupPOD.qrMarkup(temp)||''}catch(_){qr=''}}var status=pickedUp?'Abgeholt':started?'Teilweise abgeholt':'Offen',statusClass=pickedUp?'green':started?'orange':'gray',qrBlocked=started&&!runtime;return '<article data-rc1017-subshipment="'+esc(sub.subShipmentId)+'" style="border:1px solid #cbd5e1;border-radius:14px;padding:12px;background:#fff"><div style="display:flex;justify-content:space-between;gap:8px;align-items:flex-start"><div><b>'+esc(label)+'</b><div class="muted">'+metrics.colli+' Collis · '+metrics.weight.toLocaleString('de-DE',{maximumFractionDigits:1})+' kg · '+metrics.ldm.toLocaleString('de-DE',{maximumFractionDigits:2})+' LDM</div></div><span class="pill '+statusClass+'">'+status+'</span></div><div data-rc1017-qr-preview="'+esc(sub.subShipmentId)+'" style="margin-top:8px">'+qr+'</div><div class="toolbar" style="margin-top:10px"><button type="button" class="ghost" data-action="rc1017-qr-subshipment" data-subshipment-id="'+esc(sub.subShipmentId)+'" '+(qrBlocked?'disabled title="QR ist nach begonnener Abholung gesperrt"':'')+'>'+((runtime&&q(runtime.token))?'QR anzeigen':'QR-Code')+'</button><button type="button" class="ghost" data-action="rc1017-print-subshipment" data-subshipment-id="'+esc(sub.subShipmentId)+'" '+(qrBlocked?'disabled title="Aktiver QR kann nach begonnener Abholung nicht neu erzeugt werden"':'')+'>Ladeliste</button><button type="button" class="ghost" data-action="rc1017-stow-subshipment" data-subshipment-id="'+esc(sub.subShipmentId)+'">Stauplan</button></div></article>'}).join('')+'</div>';
 section.addEventListener('click',function(event){var button=event.target&&event.target.closest&&event.target.closest('button[data-action][data-subshipment-id]');if(!button||!section.contains(button)||button.disabled)return;var action=button.getAttribute('data-action'),id=button.getAttribute('data-subshipment-id');if(action==='rc1017-qr-subshipment'){rc1017ActivateSubShipmentQr(id,button);return}if(action==='rc1017-print-subshipment'){rc1017PrintSubShipment(id,button);return}if(action==='rc1017-stow-subshipment'){rc1017PrintSubShipmentStow(id);return}});card.appendChild(section);return count
}`;
replaceOne(oldRender,newRender,'renderRc1017SubShipments');

const oldShipmentCard=`function shipmentCard(sh){var id=shipmentId(sh),ref=shipmentRef(sh)||id,d=shipmentPickup(sh),days=dayDiff(d,localISO());return '<article class="index236-item is-overdue"><div class="index236-item-head"><div><h3>'+esc(ref)+'</h3><p>'+esc(shipmentCustomer(sh)||'Ohne Kunde')+' · Abholung '+esc(fmtDate(d))+'</p></div><span class="pill red">'+days+' Tag'+(days===1?'':'e')+' überfällig</span></div><div class="index236-date-row"><input type="date" value="'+esc(addDays(localISO(),1))+'" data-index236-pickup-date="'+esc(id)+'"><button class="ghost" data-index236-action="set-pickup" data-id="'+esc(id)+'">Neues Abholdatum</button></div><div class="actions"><button class="btn" data-index236-action="open-shipment" data-id="'+esc(id)+'">Sendung öffnen</button></div>'+reminderButtons(sh)+'</article>'}`;
const newShipmentCard=`function shipmentCard(sh){var id=shipmentId(sh),ref=shipmentRef(sh)||id,d=shipmentPickup(sh),days=dayDiff(d,localISO()),subs=Array.isArray(sh&&sh.subShipments)?sh.subShipments:[],picked=subs.filter(function(x){return /confirmed|picked|abgeholt|pod|completed|abgeschlossen/i.test(String(x&&x.status||''))}).length,subProgress=subs.length>1?'<p class="muted">'+subs.length+' Teilsendungen · '+picked+' von '+subs.length+' abgeholt</p>':'';return '<article class="index236-item is-overdue"><div class="index236-item-head"><div><h3>'+esc(ref)+'</h3><p>'+esc(shipmentCustomer(sh)||'Ohne Kunde')+' · Abholung '+esc(fmtDate(d))+'</p>'+subProgress+'</div><span class="pill red">'+days+' Tag'+(days===1?'':'e')+' überfällig</span></div><div class="index236-date-row"><input type="date" value="'+esc(addDays(localISO(),1))+'" data-index236-pickup-date="'+esc(id)+'"><button class="ghost" data-index236-action="set-pickup" data-id="'+esc(id)+'">Neues Abholdatum</button></div><div class="actions"><button class="btn" data-index236-action="open-shipment" data-id="'+esc(id)+'">Sendung öffnen</button></div>'+reminderButtons(sh)+'</article>'}`;
replaceOne(oldShipmentCard,newShipmentCard,'shipmentCard');

replaceOne("function loadHtml(sh,withQr){var rs=rows(sh)","function loadHtml(sh,withQr){var rc1017Child=!!(sh&&sh.rc1017SubShipmentDocument===true),rc1017ChildBanner=rc1017Child?'<div class=\"rc1017-document-subshipment\" style=\"display:flex;justify-content:space-between;gap:12px;align-items:center;margin:0 0 10px;padding:8px 10px;border:2px solid #2563eb;border-radius:10px;background:#eff6ff;color:#08245d\"><b>'+esc(sh.subShipmentLabel||'Teilsendung')+'</b><span>Hauptreferenz: '+esc(sh.rc1017ParentReference||sref(sh)||sid(sh))+'</span></div>':'';var rs=rows(sh)",'loadHtml start');
replaceOne("data-shipment-ref=\"'+ref+'\"><div class=\"rc390-head\">","data-shipment-ref=\"'+ref+'\">'+rc1017ChildBanner+'<div class=\"rc390-head\">",'loadHtml banner');

const oldCache=`function documentCacheKey(sh){var r=rows(sh),stamp=q(sh&&(sh.updatedAt||sh.modifiedAt||sh.lastModified||sh.createdAt)),parts=[sid(sh),sref(sh),stamp,cname(sh),caddress(sh),q(sh&&sh.goodsDescription),q(sh&&sh.pickupDate),q(sh&&sh.status),String(r.length),String(totals(sh).count),String(totals(sh).weight),String(totals(sh).ldm)];return parts.join('|')}`;
const newCache=`function documentCacheKey(sh){var r=rows(sh),stamp=q(sh&&(sh.updatedAt||sh.modifiedAt||sh.lastModified||sh.createdAt)),parts=[sid(sh),sref(sh),q(sh&&sh.subShipmentId),q(sh&&sh.subShipmentLabel),String(!!(sh&&sh.rc1017SubShipmentDocument)),stamp,cname(sh),caddress(sh),q(sh&&sh.goodsDescription),q(sh&&sh.pickupDate),q(sh&&sh.status),String(r.length),String(totals(sh).count),String(totals(sh).weight),String(totals(sh).ldm)];return parts.join('|')}`;
replaceOne(oldCache,newCache,'documentCacheKey');
replaceOne("decorateDocument(sh,doc,outputMode);stripQrForPdf(root);","decorateDocument(sh,doc,outputMode);if(!(sh&&sh.rc1017KeepQrInPdf===true))stripQrForPdf(root);",'conditional PDF QR strip');
replaceOne("async function downloadDocument(mode,button){","window.__EXPORTHUB_RC1017_DOWNLOAD_SUBSHIPMENT__=async function(sh,name){var out=await createPdf('load1',sh);downloadBlob(out.blob,name);return out};\nasync function downloadDocument(mode,button){",'subshipment PDF bridge');

replaceOne("if(card.dataset.sig===sig&&card.querySelector('.rc717-shell')&&card.querySelector('#rc713VehicleType')){rc710StowDirty=false;card.removeAttribute('data-rc710-stow-dirty');return true;}","if(card.dataset.sig===sig&&card.querySelector('.rc717-shell')&&card.querySelector('#rc713VehicleType')){rc710StowDirty=false;card.removeAttribute('data-rc710-stow-dirty');renderRc1017SubShipments({requiredTruckCount:shipment().requiredTruckCount,subShipments:shipment().subShipments});return true;}",'stow unchanged refresh');
replaceOne("var cab=card.querySelector('.rc717-cab');if(cab&&vehicle.kind==='container')cab.style.display='none';\n return true","var cab=card.querySelector('.rc717-cab');if(cab&&vehicle.kind==='container')cab.style.display='none';\n renderRc1017SubShipments({requiredTruckCount:shipment().requiredTruckCount,subShipments:shipment().subShipments});\n return true",'stow final child render');

fs.writeFileSync(path,src);
console.log('RC1017 task7 applied');
