'use strict';
const fs=require('fs');
const path='api/shared/pickup-store.js';
let src=fs.readFileSync(path,'utf8');
if(src.includes('function rc1017UpdateSubShipmentTeam(')){
  console.log('RC1017 task6 already applied');
  process.exit(0);
}
const helper=`
function rc1017SafePickupHistory(history){return(Array.isArray(history)?history:[]).map(x=>({id:x.id||('pickup-'+(x.sequence||'')),sequence:Number(x.sequence||0)||0,type:x.type||(x.complete?'complete':'partial'),confirmedAt:x.confirmedAt||'',colliCount:Math.max(0,Math.round(Number(x.colliCount)||0)),collectedAfter:Math.max(0,Math.round(Number(x.collectedAfter)||0)),remainingAfter:Math.max(0,Math.round(Number(x.remainingAfter)||0)),complete:x.complete===true,driverName:x.driverName||'',licensePlate:x.licensePlate||'',loaderName:x.loaderName||'',loaderId:x.loaderId||'',carrierName:x.carrierName||'',returnedEuroPallets:Math.max(0,Math.round(Number(x.returnedEuroPallets)||0)),signatureStored:!!x.signatureBlobName,signatureBlobName:x.signatureBlobName||'',signatureStoredAt:x.signatureStoredAt||''}))}
function rc1017SubPicked(sub){return['confirmed','pod','completed','abgeholt','pod vorhanden','abgeschlossen'].includes(String(sub&&sub.status||'').trim().toLowerCase())}
function rc1017SubStarted(sub){return!!(sub&&(sub.locked===true||['partial','confirmed','pod','completed','teilweise abgeholt','abgeholt','pod vorhanden','abgeschlossen'].includes(String(sub.status||'').trim().toLowerCase())))}
function rc1017SubHasPod(sub){return!!(sub&&((Array.isArray(sub.podFiles)&&sub.podFiles.length>0)||sub.signatureBlobName))}
function rc1017AggregateShipmentFromSubs(sh,iso){const subs=Array.isArray(sh&&sh.subShipments)?sh.subShipments:[];if(subs.length<2)return sh;const allPicked=subs.every(rc1017SubPicked),anyStarted=subs.some(rc1017SubStarted),allPod=subs.every(rc1017SubHasPod);sh.multiTruckLocked=subs.some(x=>x&&x.locked===true);sh.collectedPickupCollis=subs.reduce((n,x)=>n+Math.max(0,Math.round(Number(x&&x.pickupCollectedColliCount||x&&x.collectedPickupCollis)||0)),0);sh.pickupCollectedColliCount=sh.collectedPickupCollis;sh.remainingPickupCollis=subs.reduce((n,x)=>n+Math.max(0,Math.round(Number(x&&x.pickupRemainingColliCount||x&&x.remainingPickupCollis)||0)),0);sh.pickupRemainingColliCount=sh.remainingPickupCollis;sh.expectedColliCount=subs.reduce((n,x)=>n+Math.max(0,Math.round(Number(x&&x.expectedColliCount)||0)),0);sh.pickupPartial=!allPicked&&anyStarted;sh.pickupComplete=allPicked;sh._syncUpdatedAt=iso;sh._syncDeviceId='qr-pickup';if(allPicked){sh.status='Abgeholt';sh.processStatus='Abgeholt';sh.pickedUp=true;sh.pickupStatus='abgeholt';sh.pickupConfirmed=true;sh.pickupRegistered=true;sh.pickupConfirmedAt=iso;sh.pickedUpAt=iso;if(!sh.actualPickupDate)sh.actualPickupDate=String(iso||'').slice(0,10);if(allPod){sh.podStatus='POD vorhanden';sh.hasPod=true}}else if(anyStarted){sh.status='Teilweise abgeholt';sh.processStatus='Teilweise abgeholt';sh.pickedUp=false;sh.pickupStatus='teilweise abgeholt';sh.pickupConfirmed=false}return sh}
function rc1017UpdateSubShipmentTeam(sh,record,history,complete,collected,remaining,iso){const subs=Array.isArray(sh&&sh.subShipments)?sh.subShipments:[],id=String(record&&record.subShipmentId||''),index=subs.findIndex(x=>String(x&&x.subShipmentId||'')===id);if(index<0)throw err('SUBSHIPMENT_NOT_FOUND','Teilsendung wurde in der Hauptsendung nicht gefunden.',409);const safeHistory=rc1017SafePickupHistory(history),last=safeHistory.length?safeHistory[safeHistory.length-1]:null,files=realPodFiles(record),next=Object.assign({},subs[index],{subShipmentId:id,subShipmentSequence:Number(record.subShipmentSequence||subs[index].subShipmentSequence||subs[index].sequence||0)||0,subShipmentTotal:Number(record.subShipmentTotal||subs.length)||subs.length,subShipmentLabel:record.subShipmentLabel||subs[index].subShipmentLabel||subs[index].label||'',status:complete?'confirmed':(collected>0?'partial':'open'),locked:collected>0||complete,pickupHistory:safeHistory,collectedPickupCollis:collected,pickupCollectedColliCount:collected,remainingPickupCollis:remaining,pickupRemainingColliCount:remaining,expectedColliCount:expectedCollis(record),confirmedAt:complete?(record.confirmedAt||last&&last.confirmedAt||iso):null,lastPartialPickupAt:record.lastPartialPickupAt||(!complete&&last&&last.confirmedAt)||null,podFiles:files,signatureBlobName:record.signatureBlobName||last&&last.signatureBlobName||'',signatureStoredAt:record.signatureStoredAt||last&&last.signatureStoredAt||'',pickupRegistered:true,pickupAccessKeyHash:record.accessKey||subs[index].pickupAccessKeyHash||'',updatedAt:iso});sh.subShipments=subs.map((x,i)=>i===index?next:x);return rc1017AggregateShipmentFromSubs(sh,iso)}
`;
const fnAnchor='async function updateTeam(record,podsToAdd=[],rawToken=\'\'){';
if(!src.includes(fnAnchor))throw new Error('updateTeam anchor not found');
src=src.replace(fnAnchor,helper+'\n'+fnAnchor);
const old="  if(sh){const iso=String(last&&last.confirmedAt||record.confirmedAt||record.lastPartialPickupAt||now()),carrier=sanitizeText(first(record,['carrierName','speditionName','carrier','spedition']),180);";
const next="  if(sh&&record.subShipmentId){const iso=String(last&&last.confirmedAt||record.confirmedAt||record.lastPartialPickupAt||now());rc1017UpdateSubShipmentTeam(sh,record,history,complete,collected,remaining,iso)}\n  if(sh&&!record.subShipmentId){const iso=String(last&&last.confirmedAt||record.confirmedAt||record.lastPartialPickupAt||now()),carrier=sanitizeText(first(record,['carrierName','speditionName','carrier','spedition']),180);";
if(!src.includes(old))throw new Error('updateTeam shipment branch anchor not found');
src=src.replace(old,next);
fs.writeFileSync(path,src);
console.log('RC1017 task6 applied');
